#####This script contains the list of comments that appear in stream chat for vignette 1.
#####It also contains the possible reactions the player can make toward chat for vignette 1.


#Chats that are already present when the game starts - scene 1
default vig1_sc1_comment1 = ChatEntry( False, "{b}Coriolis - 5:36{/b}\nHey [streamer]! So excited to start a new game!", 1, "#ffffffff")
default vig1_sc1_comment2 = ChatEntry( False, "{b}swayy0scar - 5:45{/b}\nYo sick space battle! This game has more action than I was expecting", 1, "#ffffffff")
default vig1_sc1_comment3 = ChatEntry( False, "{b}_lostinmetr0 - 5:47{/b}\nIts got some moments, but it's mostly a dialogue-based game", 1, "#ffffffff")
default vig1_sc1_comment4 = ChatEntry( False, "{b}Coriolis - 6:01{/b}\nFor real, Allistar got a glow up from the last game!", 1, "#ffffffff")
default vig1_sc1_comment5 = ChatEntry( False, "{b}kitcat - 6:10{/b}\nHihi! New to stream! This is that new RPG, yea?", 1, "#ffffffff")
default vig1_sc1_comment6 = ChatEntry( False, "{b}Coriolis - 6:11{/b}\nWelcome!", 1, "#ffffffff")
default vig1_sc1_comment7 = ChatEntry( False, "{b}kitcat - 6:14{/b}\nOoooh this mechanic is kinda hunky!", 1, "#ffffffff")
default vig1_sc1_comment8 = ChatEntry( False, "{b}_swayy0scar - 6:30{/b}\nBribing is cool, I would've gone the \"steal\" route", 1, "#ffffffff")
default vig1_sc1_comment9 = ChatEntry( False, "{b}Coriolis - 6:31{/b}\n[streamer] tends to go Marshal for moral alignment", 1, "#ffffffff")

#Chats that appear in the workshop scene
default vig1_sc2_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:35{/b}\nClearly a man of class", 1, "#ffffffff")
default vig1_sc2_comment2 = ChatEntry( True, "{b}_swayy0scar - 6:37{/b}\nWait, who's Deadeye and what's a snakehawk?", 1, "#ffffffff", "vig1_sc2_whoQuestion")
default vig1_sc2_comment2_csAma = ChatEntry( True, "{b}Coriolis - 6:37{/b}\nDeadeye was also Moze's mentor until a heist against BigCorp went wrong. Most of 'em died in the aftermath.", 1, "#ffffffff", "vig1_sc2_thankCS")
default vig1_sc2_comment2_csSH = ChatEntry( True, "{b}Coriolis - 6:37:{/b}\nSnakehawks were the gang Allistar, Moze, and Jennica were part of before they became mercenaries. It's why Allistar has the same tattoo as Moze", 1, "#ffffffff", "vig1_sc2_thankCS")
default vig1_sc2_comment3 = ChatEntry( False, "{b}_swayy0scar - 6:38{/b}\nGot it, thanks!", 1, "#ffffffff")
default vig1_sc2_comment4 = ChatEntry( False, "{b}kitcat - 6:39{/b}\nOMFG! I LOVE HIM!", 1, "#ffffffff")
default vig1_sc2_comment5 = ChatEntry( False, "{b}Coriolis - 6:42{/b}\nDEADEYE'S BACK! TIME TO GET OUTTA DODGE!", 1, "#ffffffff")
default vig1_sc2_comment6 = ChatEntry( True, "{b}_lostinmetr0 - 6:45{/b}\nHe kinda is a hunk haha", 1, "#ffffffff", "vig1_sc2_allistarhunk")

#Chats that appear in the shootout scene
default vig1_sc2_comment7 = ChatEntry( False, "{b}_swayy0scar - 6:46{/b}\nIt's High Noon!", 1, "#ffffffff")
default vig1_sc2_comment8_kc = ChatEntry( False, "{b}kitcat - 6:48{/b}\nwoahwoahwoahwoah, no need to be rude", 1, "#ffffffff")
default vig1_sc2_comment9 = ChatEntry( False, "{b}kitcat - 6:50{/b}\nShoot the speeder!", 1, "#ffffffff")
default vig1_sc2_comment10 = ChatEntry( False, "{b}Coriolis - 6:50{/b}\nAllistar's in a baaaaad spot", 1, "#ffffffff")
default vig1_sc2_comment11 = ChatEntry( False, "{b}kitcat - 6:52{/b}\nKILL. THIS. MAN.", 1, "#ffffffff")
default vig1_sc2_comment12 = ChatEntry( False, "{b}_lostinmetr0 - 6:56{/b}\nClean play, clean play", 1, "#ffffffff")
default vig1_sc2_comment13 = ChatEntry( False, "{b}_swayy0scar - 6:56{/b}\nI mean I wouldn't have done much better tbf ahaha", 1, "#ffffffff")
default vig1_sc2_comment14 = ChatEntry( False, "{b}kitcat - 7:06{/b}\nNOOOO!!!", 1, "#ffffffff")
default vig1_sc2_comment15 = ChatEntry( False, "{b}kitcat - 7:07{/b}\nphew! That was a close one", 1, "#ffffffff")
default vig1_sc2_comment16 = ChatEntry( True, "{b}Coriolis - 7:07{/b}\nFor a second there I thought you were gonna go with the collateral damage, [streamer]", 1, "#ffffffff", "vig1_sc2_houseExplosion")
default vig1_sc2_comment17 = ChatEntry( False, "{b}kitcat - 7:13{/b}\noooh they're pretty!", 1, "#ffffffff")

#Scene 3 chats (appear back on ship)
default vig1_sc3_comment1 = ChatEntry( False, "{b}swayy0scar - 7:16{/b}\nSpaceships are so cool", 1, "#ffffffff")
default vig1_sc3_raid_comment1 = ChatEntry( False, "{b}pickledDragons - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment2 = ChatEntry( False, "{b}xXpearlXx - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment3 = ChatEntry( False, "{b}_drdre4d_ - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment4 = ChatEntry( False, "{b}LethalEthan - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment5 = ChatEntry( False, "{b}AFKAngel - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment6 = ChatEntry( False, "{b}8bitBANDIT - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment7 = ChatEntry( False, "{b}R4dio_Robbie - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment8 = ChatEntry( False, "{b}darthMEOW94 - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment9 = ChatEntry( False, "{b}turbog00se1 - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment10 = ChatEntry( False, "{b}llamabama22 - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment11 = ChatEntry( False, "{b}virgom00n - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment12 = ChatEntry( False, "{b}shnzi - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_raid_comment13 = ChatEntry( False, "{b}duckduckdi3 - 7:19{/b}\nPut 'em up, this is a Bandit raid!", 1, "#ffffffff")
default vig1_sc3_comment2 = ChatEntry( False, "{b}Coriolis - 7:19{/b}\nWelcome!", 1, "#ffffffff")
default vig1_sc3_comment3_bandit0 = ChatEntry( False, "{b}8bitBANDIT - 7:20{/b}\nHiya [streamer], good to be here! You a big Oakley fan?", 1, "#ffffffff", "vig1_sc3_banditConvo")
default vig1_sc3_comment3_bandit1 = ChatEntry( False, "{b}8bitBANDIT - 7:21{/b}\nNice! Wouldn't say I'm a huge fan or anything. Got to Oakely 1 just a couple months ago, but really into the world and characters!", 1, "#ffffffff")
default vig1_sc3_comment3_bandit2 = ChatEntry( False, "{b}8bitBANDIT - 7:21{/b}\nYou a Marshal or Outlaw Moze?", 1, "#ffffffff")
default vig1_sc3_comment3_bandit3 = ChatEntry( False, "{b}8bitBANDIT - 7:22{/b}\nI get that, I'm lowkey similar lolol", 1, "#ffffffff")
default vig1_sc3_comment3_bandit4 = ChatEntry( False, "{b}8bitBANDIT - 7:21{/b}\nIt's cute that this is a sentimental thing with your fam!", 1, "#ffffffff")
default vig1_sc3_comment3_bandit5 = ChatEntry( False, "{b}8bitBANDIT - 7:24{/b}\nOoooh that's a tough one", 1, "#ffffffff")
default vig1_sc3_comment3_bandit6 = ChatEntry( False, "{b}8bitBANDIT - 7:24{/b}\nIt may be recency bias, but I'm gonna go MAC. He's just so cute and fun!", 1, "#ffffffff")
default vig1_sc3_comment3_bandit7 = ChatEntry( False, "{b}8bitBANDIT - 7:25{/b}\nAlright, my turn: who's your favourite character?", 1, "#ffffffff")
default vig1_sc3_comment3_banditAllistar = ChatEntry( False, "{b}8bitBANDIT - 7:27{/b}\nAhhhh that should make things interesting then ;)", 1, "#ffffffff")
default vig1_sc3_comment3_bandit8 = ChatEntry( False, "{b}8bitBANDIT - 7:27{/b}\nHe's great!", 1, "#ffffffff")
default vig1_sc3_comment3_bandit9 = ChatEntry( False, "{b}8bitBANDIT - 7:27{/b}\nPeople are speculating that your choices might affect his personality which could be very interesting too", 1, "#ffffffff")
default vig1_sc3_comment3_bandit10 = ChatEntry( False, "{b}8bitBANDIT - 7:27{/b}\nAhh likes an engineer with a little Utilitarian energy, I see you", 1, "#ffffffff")
default vig1_sc3_comment3_bandit11 = ChatEntry( False, "{b}8bitBANDIT - 7:27{/b}\nCan't go wrong with the classics! Jennica's so sweet!", 1, "#ffffffff")


#Resume normal flow
default vig1_sc3_comment5 = ChatEntry( False, "{b}virgom00n - 7:29{/b}\nAh this part hurts so much!", 1, "#ffffffff")
default vig1_sc3_comment6 = ChatEntry( False, "{b}swayy0scar - 7:29{/b}\nHey, no spoilers!", 1, "#ffffffff")
default vig1_sc3_comment7 = ChatEntry( False, "{b}kitcat - 7:30{/b}\nOh heeell no, so this is a hunk with a death wish", 1, "#ffffffff")
default vig1_sc3_comment8 = ChatEntry( False, "{b}LethalEthan - 7:30{/b}\nEvery time I try to get out, they pull me back in", 1, "#ffffffff")
default vig1_sc3_suspicion_callback = ChatEntry( False, "{b}Coriolis - 7:30{/b}\n[streamer], you called it!", 1, "#ffffffff")
default vig1_sc3_comment9 = ChatEntry( False, "{b}pickledDragons - 7:30{/b}\nThis self-righteous prick", 1, "#ffffffff")
default vig1_sc3_comment10 = ChatEntry( False, "{b}darthMEOW94 - 7:31{/b}\nMaybe [streamer] will be the one to take him to task", 1, "#ffffffff")
default vig1_sc3_comment11 = ChatEntry( False, "{b}8bitBANDIT - 7:31{/b}\nJudge me all you want I feel good about my choice!", 1, "#ffffffff")
default vig1_sc3_comment12 = ChatEntry( False, "{b}pickledDragons - 7:32{/b}\nOutlaws gotta get their hands dirty", 1, "#ffffffff")
default vig1_sc3_comment13 = ChatEntry( False, "{b}kitcat - 7:32{/b}\nHe's threatening MAC, he's gotta go", 1, "#ffffffff")
default vig1_sc3_comment14 = ChatEntry( False, "{b}swayy0scar - 7:32{/b}\nahhhhh the hunky mechanic is breaking my heart!", 1, "#ffffffff")
default vig1_sc3_comment15 = ChatEntry( False, "{b}virgom00n - 7:32{/b}\ntold ya", 1, "#ffffffff")
default vig1_sc3_comment16 = ChatEntry( False, "{b}Coriolis - 7:32{/b}\nNot Allistar!", 1, "#ffffffff")

#Scene 3 chats for after killing Allistar
default vig1_sc3_shot_comment1 = ChatEntry( False, "{b}pickledDragons - 7:33{/b}\nNO WAY!", 1, "#ffffffff")
default vig1_sc3_shot_comment2 = ChatEntry( False, "{b}Coriolis - 7:33{/b}\nI am shook!", 1, "#ffffffff")
default vig1_sc3_shot_comment3 = ChatEntry( False, "{b}kitcat - 7:33{/b}\nYou touch MAC, you get whacked", 1, "#ffffffff")
default vig1_sc3_shot_mistake_comment1 = ChatEntry( False, "{b}swayy0scar - 7:33{/b}\nthe ol fat finger", 1, "#ffffffff")
default vig1_sc3_shot_mistake_comment2 = ChatEntry( False, "{b}virgom00n - 7:34{/b}\nSave scum?", 1, "#ffffffff")
default vig1_sc3_shot_mistake_comment3 = ChatEntry( False, "{b}LethalEthan - 7:34{/b}\nNahhh, that's a slippery slope", 1, "#ffffffff")
default vig1_sc3_shot_cool_comment1 = ChatEntry( False, "{b}llamabama22 - 7:33{/b}\nAHA like the name of the game", 1, "#ffffffff")
default vig1_sc3_shot_cool_comment2 = ChatEntry( False, "{b}turbog00se1 - 7:34{/b}\nWe'll work on it", 1, "#ffffffff")
default vig1_sc3_shot_shout_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 7:33{/b}\nHunk down! Who's got a rez?", 1, "#ffffffff")
default vig1_sc3_shot_shout_comment2 = ChatEntry( False, "{b}LethalEthan - 7:33{/b}\nBro is SUPER dead", 1, "#ffffffff")
default vig1_sc3_shot_shout_comment3 = ChatEntry( False, "{b}8bitBANDIT - 7:34{/b}\nLike, incredibly deceased", 1, "#ffffffff")
default vig1_sc3_shot_shout_comment4 = ChatEntry( False, "{b}duckduckdi3 - 7:34{/b}\nOmega dead", 1, "#ffffffff")
default vig1_sc3_shot_comment4 = ChatEntry( False, "{b}shnzi - 7:34{/b}\nProbly both tbh", 1, "#ffffffff")
default vig1_sc3_shot_comment5 = ChatEntry( False, "{b}8bitBANDIT - 7:35{/b}\nCan't believe you can actually kill off Allistar", 1, "#ffffffff")
default vig1_sc3_shot_comment6 = ChatEntry( False, "{b}AFKAngel - 7:35{/b}\n[streamer] the real outlaw", 1, "#ffffffff")
default vig1_sc3_shot_comment7 = ChatEntry( False, "{b}darthMEOW94 - 7:35{/b}\nUltra omega dead", 1, "#ffffffff")
default vig1_sc3_shot_comment8 = ChatEntry( False, "{b}kitcat - 7:36{/b}\nhis circuits can't compute! *hug emoji*", 1, "#ffffffff")
default vig1_sc3_shot_comment9 = ChatEntry( False, "{b}pickledDragons - 7:36{/b}\nI'm so curious how this will change the story", 1, "#ffffffff")
default vig1_sc3_shot_comment10 = ChatEntry( False, "{b}Coriolis - 7:37{/b}\nThat's how it ends!?", 1, "#ffffffff")
default vig1_sc3_shot_comment11 = ChatEntry( False, "{b}virgom00n - 7:37{/b}\nyep", 1, "#ffffffff")
default vig1_sc3_shot_comment12 = ChatEntry( False, "{b}Coriolis - 7:38{/b}\nI'm still processing", 1, "#ffffffff")
default vig1_sc3_end_olds_comment1 = ChatEntry( False, "{b}swayy0scar - 7:38{/b}\nayyyyy", 1, "#ffffffff")
default vig1_sc3_end_olds_comment2 = ChatEntry( False, "{b}8bitBANDIT - 7:38{/b}\nThis was sick!", 1, "#ffffffff")
default vig1_sc3_end_next_comment1 = ChatEntry( False, "{b}kitcat - 7:39{/b}\nMAC is safe and that's what matters", 1, "#ffffffff")
default vig1_sc3_signoff_comment1 = ChatEntry( False, "{b}swayy0scar - 7:39{/b}\nI might just pick this game up myself. Thanks for the stream!", 1, "#ffffffff")
default vig1_sc3_signoff_comment2 = ChatEntry ( False, "{b}LethalEthan - 7:39{/b}\nsayonara", 1, "#ffffffff")
default vig1_sc3_signoff_comment3 = ChatEntry( False, "{b}darthMEOW94 - 7:39{/b}\nadios!", 1, "#ffffffff")
default vig1_sc3_signoff_comment4 = ChatEntry( False, "{b}Coriolis - 7:39{/b}\nFor anyone who wants to join for the next one, we'll be back here every Wednesday when the next episode drops!", 1, "#ffffffff")
default vig1_sc3_signoff_comment5 = ChatEntry( False, "{b}8bitBANDIT - 7:39{/b}\nGreat stream! Night everyone!", 1, "#ffffffff")
default vig1_sc3_signoff_comment6 = ChatEntry( False, "{b}virgom00n - 7:39{/b}\nBye!", 1, "#ffffffff")
default vig1_sc3_signoff_comment7 = ChatEntry( False, "{b}turbog00se1 - 7:39{/b}\nFun times!", 1, "#ffffffff")
default vig1_sc3_signoff_comment8 = ChatEntry( False, "{b}llamabama22 - 7:40{/b}\nThx for the stream!", 1, "#ffffffff")
default vig1_sc3_signoff_comment9 = ChatEntry( False, "{b}pickledDragons - 7:40{/b}\nAwesome stream, stoked for next one!", 1, "#ffffffff")
default vig1_sc3_signoff_comment10 = ChatEntry( False, "{b}kitcat - 7:40{/b}\nNight!", 1, "#ffffffff")
#default vig1_sc3_shot_comment
#default vig1_sc3_shot_comment
#default vig1_sc3_shot_comment

#List of moments that the streamer can initiate
default vig1_sc2_streamer1 = ChatEntry( True, "REACT", 1, "#ffffffff", "vig1_sc2_combatReact")
default vig2_sc3_streamer1 = ChatEntry( True, "REACT", 1, "#ffffffff")

#trying to create list of blueitthreads to display properly
default vig1_bThread1 = bThread( 1, "vig1_blueit_firstchoice", "images/socials/bThread_firstChoice.png") #tag, target, image
default vig1_bThread2 = bThread( 1, "vig1_blueit_firstgame", "images/socials/bThread_firstGame.png")
default vig1_bThread3 = bThread( 1, "vig1_blueit_romance", "images/socials/bThread_romance.png")
default vig1_bThread4 = bThread( 2, "vig1_blueit_glitch", "images/socials/bThread_glitch.png")