###This script contains the chatter comments for Vignette 2

#Comments in Scene 1
default vig2_sc1_comment1 = ChatEntry( False, "{b}Coriolis - 5:40{/b}\nI just got the live notification!", 2, "#ffffff")
default vig2_sc1_comment2 = ChatEntry( True, "{b}Coriolis - 5:41{/b}\nIt's just after class for you right? How did that test go?", 2, "#ffffff", "vig2_sc1_testquestion")
default vig2_sc1_comment3 = ChatEntry( False, "{b}Squeejieboy33 - 5:42{/b}\nehh back again! the ending last time was nuts", 2, "#ffffff")
default vig2_sc1_comment4 = ChatEntry( False, "{b}kitcat - 5:44{/b}\nhey everyone!! ah im pumped for this one!", 2, "#ffffff")
default vig2_sc1_comment5 = ChatEntry( False, "{b}_lostinmetr0 - 5:46{/b}\ndoes anyone know if this is the whole crew?", 2, "#ffffff")
default vig2_sc1_comment6 = ChatEntry( False, "{b}AFKAngel - 5:46{/b}\ndunno. havent played yet.", 2, "#ffffff")
default vig2_sc1_comment7 = ChatEntry( False, "{b}kitcat - 5:47{/b}\nfrom where im at, yup that's it!", 2, "#ffffff")
default vig2_sc1_comment8 = ChatEntry( False, "{b}turb0g00se - 5:47{/b}\nmatticus alignment might give some interesting options", 2, "#ffffff")
default vig2_sc1_comment9 = ChatEntry( False, "{b}_lostinmetr0 - 5:47{/b}\nyeah it would give them a lot more access to the underground.", 2, "#ffffff")
default vig2_sc1_comment10 = ChatEntry( False, "{b}Coriolis - 5:48{/b}\nif [streamer] can convince him! like in the {i}Treck Down{/i} stream with the underworlder chief.", 2, "#ffffff")
default vig2_sc1_comment11 = ChatEntry( False, "{b}turb0g00se - 5:48{/b}\ntrue true", 2, "#ffffff")
default vig2_sc1_comment12 = ChatEntry( False, "{b}PickledDragons - 5:49{/b}\nyeah and definitely would lead to some shenanigans", 2, "#ffffff")
default vig2_sc1_comment13 = ChatEntry( True, "{b}shnzi - 5:49{/b}\nnew to stream! did you like matticus in the first game?", 2, "#ffffff", "vig2_sc1_matticusopinion")
default vig2_sc1_comment14 = ChatEntry( False, "{b}kitcat - 5:51{/b}\nouh yeah! let my lil guy MAC out to see the world!", 2, "#ffffff")

#Comments in Scene 1 Chat Responses
default vig2_sc1_coriolis_comment1 = ChatEntry( False, "{b}Coriolis - 5:41{/b}\nof course! I'm glad it went well!", 2, "#ffffff")
default vig2_sc1_coriolis_comment2 = ChatEntry( False, "{b}Coriolis - 5:41{/b}\nOh I'm sorry to hear that, I hope your grade comes back ok!", 2, "#ffffff")
default vig2_sc1_kitcat_comment1 = ChatEntry( False, "{b}kitcat - 5:49{/b}\nHot take alert haha", 2, "#ffffff")
default vig2_sc1_kitcat_comment2 = ChatEntry( False, "{b}kitcat - 5:49{/b}\nwow someone with a genuine hot take on this game, heck yea!", 2, "#ffffff")

#Comments in Scene 2
default vig2_sc2_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 5:53{/b}\nI too am a hater of customs. just an airport hater in general.", 2, "#ffffff")
default vig2_sc2_comment2 = ChatEntry( False, "{b}turb0g00se - 5:54{/b}\nfr", 2, "#ffffff")
default vig2_sc2_comment3 = ChatEntry( False, "{b}AFKAngel - 5:55{/b}\nteresa OP", 2, "#ffffff")
default vig2_sc2_comment4 = ChatEntry( False, "{b}PickledDragons - 5:55{/b}\nugh wait is this whole chapter just a stealth thing?", 2, "#ffffff")
default vig2_sc2_comment5 = ChatEntry( False, "{b}kitcat - 5:58{/b}\nStealth Mission. Gaming Trope. Typically boring but allows for good character moments.", 2, "#ffffff")
default vig2_sc2_comment6 = ChatEntry( False, "{b}shnzi - 5:58{/b}\nLOL", 2, "#ffffff")
default vig2_sc2_comment7 = ChatEntry( False, "{b}PickledDragons - 6:00{/b}\nok no teresa has my vote, quick and easy getaway", 2, "#ffffff")

#Comments in Scene 2 - Marshall Choice
default vig2_sc2_mar_comment1 = ChatEntry( False, "{b}Coriolis - 6:00{/b}\nyeah safe bet for sure", 2, "#ffffff")
default vig2_sc2_mar_comment2 = ChatEntry( False, "{b}kitcat - 6:01{/b}\nthese aren't the outlaws you're looking for", 2, "#ffffff")
default vig2_sc2_mar_comment3 = ChatEntry( True, "{b}J4MIR0QU4I - 6:01{/b}\nmeh after last time does this even make sense for the crew?", 2, "#ffffff", "vig2_sc2_mar_consistency")
default vig2_sc2_mar_J4MresponseMAR = ChatEntry( False, "{b}J4MIR0QU4I - 6:01{/b}\nbooooooo", 2, "#ffffff")
default vig2_sc2_mar_J4MresponseOUT = ChatEntry( False, "{b}J4MIR0QU4I - 6:01{/b}\nhell yeah, this is why I'm here!", 2, "#ffffff")
default vig2_sc2_mar_comment4 = ChatEntry( False, "{b}_lostinmetr0 - 6:01{/b}\nwdym", 2, "#ffffff")
default vig2_sc2_mar_comment5 = ChatEntry( False, "{b}Coriolis - 6:02{/b}\nlast stream took a darker turn", 2, "#ffffff")
default vig2_sc2_mar_comment6 = ChatEntry( False, "{b}_lostinmetr0 - 6:03{/b}\nohh okok", 2, "#ffffff")
default vig2_sc2_mar_comment7 = ChatEntry( False, "{b}shnzi - 6:04{/b}\nme too I picked bribe", 2, "#ffffff")
default vig2_sc2_mar_comment8 = ChatEntry( False, "{b}turb0g00se - 6:05{/b}\nsmart man, I also hate my job", 2, "#ffffff")
default vig2_sc2_mar_comment9 = ChatEntry( False, "{b}AFKAngel - 6:06{/b}\nfor sure he took the money and ran", 2, "#ffffff")
default vig2_sc2_mar_comment10 = ChatEntry( False, "{b}bacon8r_6 - 6:08{/b}\nperfect ad time, no idea what's going on now", 2, "#ffffff")

#Comments in Scene 2 - Outlaw Choice
default vig2_sc2_out_comment1 = ChatEntry( False, "{b}PickledDragons - 6:01{/b}\nah yes exactly, better have your fate in your own hands", 2, "#ffffff")
default vig2_sc2_out_comment2 = ChatEntry( False, "{b}Coriolis - 6:01{/b}\ncant help but agree", 2, "#ffffff")
default vig2_sc2_out_comment3 = ChatEntry( False, "{b}AFKAngel - 6:02{/b}\nlmao teresa always makes it fun", 2, "#ffffff")
default vig2_sc2_out_comment4 = ChatEntry( False, "{b}turb0g00se - 6:03{/b}\nYES literally whas the worst that can happen", 2, "#ffffff")
default vig2_sc2_out_comment5 = ChatEntry( True, "{b}shnzi - 6:05{/b}\nhey [streamer], are you romancing teresa?", 2, "#ffffff", "vig2_sc2_out_romance")
default vig2_sc2_out_comment6 = ChatEntry( False, "{b}kitcat - 6:05{/b}\nit's hard to, unless you make some whack choices", 2, "#ffffff")
default vig2_sc2_out_comment7 = ChatEntry( False, "{b}bacon8r_6 - 6:07{/b}\ndon't understand why more people don't pick what an actual outlaw crew would do", 2, "#ffffff")
default vig2_sc2_out_comment8 = ChatEntry( False, "{b}PickledDragons - 6:07{/b}\neven Jennica's having fun - crew bonding at max capacity", 2, "#ffffff")
default vig2_sc2_out_comment9 = ChatEntry( False, "{b}R4dioRobbie - 6:08{/b}\nRUBES", 2, "#ffffff")
default vig2_sc2_out_comment10 = ChatEntry( False, "{b}Coriolis - 6:09{/b}\nthat was actually so cute - go team!", 2, "#ffffff")
default vig2_sc2_out_comment11 = ChatEntry( False, "{b}AFKAngel - 6:09{/b}\neasy peasy", 2, "#ffffff")

#comments for Romance Decision
default vig2_sc2_romance_ama1 = ChatEntry (False, "{b}PickledDragons - 6:05{/b}\nYessss! OMG I want the Ama drama so bad!", 0, "#ffffff")
default vig2_sc2_romance_ama2 = ChatEntry (False, "{b}kitcat - 6:05{/b}\nTurn the big bad with love? Dig it!", 0, "#ffffff")
default vig2_sc2_romance_pilot1 = ChatEntry(False, "{b}Coriolis - 6:05{/b}\nJennica ftw!", 0, "#ffffff")
default vig2_sc2_romance_engineer1 = ChatEntry(False, "{b}KitKat - 6:05{/b}\nCrazy engineer ftw!", 0, "#ffffff")

#Comments in Scene 3
default vig2_sc3_comment1 = ChatEntry( False, "{b}Coriolis - 6:09{/b}\nyeah classic bad guy gates", 2, "#ffffff")
default vig2_sc3_comment2 = ChatEntry( False, "{b}shnzi - 6:10{/b}\ncharacter = bad is the same as character = has giant castle made of gold in generally poor area", 2, "#ffffff")
default vig2_sc3_comment3 = ChatEntry( False, "{b}kitcat - 6:10{/b}\nbrat", 2, "#ffffff")
default vig2_sc3_comment4 = ChatEntry( False, "{b}AFKAngel - 6:11{/b}:\n:P", 2, "#ffffff")

#Comments in Scene 3 - Lore
default vig2_sc3_lore_comment1 = ChatEntry( False, "{b}turb0g00se - 6:12{/b}\nwhen are we going to find out what happened at tiber iii?", 2, "#ffffff")
default vig2_sc3_lore_comment2 = ChatEntry( False, "{b}_lostinmetr0 - 6:13{/b}\nthe running gag must run", 2, "#ffffff") 

#Comments in Scene 3 - Threaten
default vig2_sc3_threat_comment1 = ChatEntry( False, "{b}R4dioRobbie - 6:12{/b}\nliterally just doing his job", 2, "#ffffff")
default vig2_sc3_threat_comment2 = ChatEntry( False, "{b}_lostinmetr0 - 6:13{/b}\nbruh so are we, just let us through", 2, "#ffffff")
default vig2_sc3_threat_comment3 = ChatEntry( False, "{b}J4MIR0QU4I - 6:13{/b}\nexaaaaactly^^", 2, "#ffffff")

#Comments in Scene 4
default vig2_sc4_comment1 = ChatEntry( True, "{b}Coriolis - 6:15{/b}\nis there a gameplan here?", 2, "#ffffff", "vig2_sc4_gameplan")
default vig2_sc4_comment2 = ChatEntry( False, "{b}kitcat - 6:20{/b}\naaaahhh, no! I don't want Matticus knowing about the lil guy!", 2, "#ffffff")
default vig2_sc4_comment3 = ChatEntry( False, "{b}PickledDragons - 6:21{/b}\nbetter the devil you know, especially when Deadeye's involved", 2, "#ffffff")
default vig2_sc4_comment4 = ChatEntry( False, "{b}shnzi - 6:23{/b}\nsmart to ally with Matticus, but not a popular choice", 2, "#ffffff")
default vig2_sc4_comment5 = ChatEntry( False, "{b}AFKAngel - 6:23{/b}\ncan't start a villain arc without a little villainty", 2, "#ffffff")
default vig2_sc4_comment6 = ChatEntry( False, "{b}PickledDragons - 6:24{/b}\nagreed and literally no one plays like that, makes it feel like these guys weren't even outlaws to begin with", 2, "#ffffff")
default vig2_sc4_comment7 = ChatEntry( False, "{b}Coriolis - 6:24{/b}\nyeah but they're \"doing better\"", 2, "#ffffff")
default vig2_sc4_comment8 = ChatEntry( False, "{b}turb0g00se - 6:24{/b}\ntrue, but literally everyone plays like matticus was never their ally", 2, "#ffffff")
default vig2_sc4_comment9 = ChatEntry( False, "{b}R4dioRobbie - 6:27{/b}\nyeah agreed, ngl that's how I did the chapter", 2, "#ffffff")
default vig2_sc4_comment10 = ChatEntry( False, "{b}shnzi - 6:28{/b}\nsame", 2, "#ffffff")

#Comments in Scene 4 - response to Matticus question
default vig2_sc4_against_comment1 = ChatEntry( False, "{b}shnzi - 6:18{/b}\nyeah I can't stand the guy", 2, "#ffffff")
default vig2_sc4_against_comment2 = ChatEntry( False, "{b}kitcat - 6:19{/b}\nliterally have no idea what he gives you because i never side with THE skeevy slum lord", 2, "#ffffff")
default vig2_sc4_ally_comment1 = ChatEntry( False, "{b}PickledDragons - 6:18{/b}\nExactly!! why wouldn't you use your contact", 2, "#ffffff")
default vig2_sc4_ally_comment2 = ChatEntry( False, "{b}bacon8r_6 - 6:18{/b}\nugh so glad someone is doing this, I heard you get much cooler plot points by allying matticus", 2, "#ffffff")
default vig2_sc4_ally_comment3 = ChatEntry( False, "{b}_lostinmetr0 - 6:19{/b}\nhe gives me the ick", 2, "#ffffff")
default vig2_sc4_ally_comment4 = ChatEntry( False, "{b}turb0g00se - 6:19{/b}\nyea but for the plot bro", 2, "#ffffff")

#Comments in Scene 5
default vig2_sc5_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:30{/b}\nokay finally the action starts", 2, "#ffffff")
default vig2_sc5_comment2 = ChatEntry( False, "{b}kitcat - 6:32{/b}\ncoudlnt bring myself to lie to the little guy", 2, "#ffffff")
default vig2_sc5_comment3 = ChatEntry( False, "{b}J4MIR0QU4I - 6:33{/b}\nit's best if he just stays their ally though", 2, "#ffffff")
default vig2_sc5_comment4 = ChatEntry( False, "{b}kitcat - 6:34{/b}\nyeah but bad/good is not a thing to teach the baby", 2, "#ffffff")
default vig2_sc5_comment5 = ChatEntry( False, "{b}shnzi - 6:33{/b}\nme neither, we all agree there", 2, "#ffffff")
default vig2_sc5_comment6 = ChatEntry( False, "{b}turb0g00se - 6:35{/b}\nreginald's a mood", 2, "#ffffff")

#Comments in Scene 6 - Marshall Infiltration
default vig2_sc6_mar_comment1 = ChatEntry( False, "{b}Coriolis - 6:36{/b}\nsir stealth is back! You got really good at it in the last game", 2, "#ffffff")
default vig2_sc6_mar_comment2 = ChatEntry( False, "{b}shnzi - 6:38{/b}\nboo okay im out this is the route I did, I know how it ends", 2, "#ffffff")
default vig2_sc6_mar_comment3 = ChatEntry( False, "{b}PickledDragons - 6:39{/b}\nquick, quiet, quite the typical choice my guy", 2, "#ffffff")
default vig2_sc6_mar_comment4 = ChatEntry( False, "{b}turb0g00se - 6:40{/b}\neven reginald thinks so! my man is a voice of the people", 2, "#ffffff")
default vig2_sc6_mar_choice1_stun_comment1 = ChatEntry( False, "{b}R4dioRobbie - 6:42{/b}\nI did that too!", 2, "#ffffff")
default vig2_sc6_mar_choice1_bluff_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:42{/b}\nme too I just trust every new face that walks into my secret base >.<", 2, "#ffffff")
default vig2_sc6_mar_choice2_stun_comment1 = ChatEntry( False, "{b}kitcat - 6:48{/b}\nnot stunned with the choice though", 2, "#ffffff")
default vig2_sc6_mar_choice2_stun_comment2 = ChatEntry( False, "{b}AFKAngel - 6:49{/b}\nwe all picked that one didn't we? :')", 2, "#ffffff")
default vig2_sc6_mar_choice2_stun_comment3 = ChatEntry( False, "{b}J4MIR0QU4I - 6:50{/b}\nwe are united in our lameness <3", 2, "#ffffff")
default vig2_sc6_mar_choice2_dist_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:50{/b}\nthe tried and true distract and run", 2, "#ffffff")
default vig2_sc6_mar_choice2_dist_comment2 = ChatEntry( False, "{b}Coriolis - 6:51{/b}\na [streamer] classic", 2, "#ffffff")

#Comments in Scene 6 - Outlaw Assault
default vig2_sc6_out_comment1 = ChatEntry( False, "{b}PickledDragons - 6:36{/b}\nYES! Outlaws being outlaws!", 2, "#ffffff")
default vig2_sc6_out_comment2 = ChatEntry( False, "{b}shnzi - 6:37{/b}\nno clue whats gonna happen", 2, "#ffffff")
default vig2_sc6_out_comment3 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:38{/b}\nis this the stream with the evil mc? just joined!", 2, "#ffffff")
default vig2_sc6_out_comment4 = ChatEntry( False, "{b}Coriolis - 6:39{/b}\nnot evil! just...okay a little evil today", 2, "#ffffff")
default vig2_sc6_out_comment5 = ChatEntry( False, "{b}kitcat - 6:40{/b}\noh poor MAC", 2, "#ffffff")
default vig2_sc6_out_comment6 = ChatEntry( False, "{b}_lostinmetr0 - 6:42{/b}\nhe's so sweet, this really shows his trust", 2, "#ffffff")
default vig2_sc6_out_comment7 = ChatEntry( False, "{b}AFKAngel - 6:42{/b}\nshoot! get him! more will come!", 2, "#ffffff")
default vig2_sc6_out_comment8 = ChatEntry( False, "{b}R4dioRobbie - 6:42{/b}\ndude this isn't a quick time event.", 2, "#ffffff")
default vig2_sc6_out_comment9 = ChatEntry( False, "{b}AFKAngel - 6:43{/b}\nright I just got caught up - it's so exciting", 2, "#ffffff")
default vig2_sc6_out_comment10 = ChatEntry( False, "{b}shnzi - 6:43{/b}\nTotally agree, this is way crazier than the stealth run!", 2, "#ffffff")
default vig2_sc6_out_shoot_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:44{/b}\nah! you got him! keep going!", 2, "#ffffff")
default vig2_sc6_out_shoot_comment2 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:44{/b}\nthe horror!", 2, "#ffffff")
default vig2_sc6_out_shoot_comment3 = ChatEntry( False, "{b}R4dioRobbie - 6:44{/b}\nLOL", 2, "#ffffff")
default vig2_sc6_out_shoot_comment4 = ChatEntry( False, "{b}turb0g00se - 6:45{/b}\nwho's the real deadeye here amirite", 2, "#ffffff")
default vig2_sc6_out_suppress_comment1 = ChatEntry( False, "{b}PickledDragons - 6:44{/b}\nbruh you already killed 2 guys", 2, "#ffffff")
default vig2_sc6_out_suppress_comment2 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:44{/b}\nfr", 2, "#ffffff")
default vig2_sc6_out_comment11 = ChatEntry( False, "{b}AFKAngel - 6:45{/b}\nI told you more would come!", 2, "#ffffff")
default vig2_sc6_out_comment12 = ChatEntry( False, "{b}kitcat - 6:45{/b}\nTHE GRENADE", 2, "#ffffff")
default vig2_sc6_out_comment13 = ChatEntry( False, "{b}Coriolis - 6:45{/b}\noh hell now I'm all caught up in it - get down lmao!!", 2, "#ffffff")
default vig2_sc6_out_comment14 = ChatEntry( False, "{b}turb0g00se - 6:45{/b}\nwho needs the quick and quiet route haha", 2, "#ffffff")
default vig2_sc6_out_comment15 = ChatEntry( False, "{b}_lostinmetr0 - 6:46{/b}\nwhat a mess!", 2, "#ffffff")
default vig2_sc6_out_comment16 = ChatEntry( False, "{b}PickledDragons - 6:47{/b}\nwell you got us this far...time to execute", 2, "#ffffff")
default vig2_sc6_out_comment17 = ChatEntry( False, "{b}Coriolis - 6:47{/b}\nbro so casually drops a \"time to execute\"", 2, "#ffffff")
default vig2_sc6_out_comment18 = ChatEntry( False, "{b}PickledDragons - 6:47{/b}\nlol well the situation calls for it!", 2, "#ffffff")
default vig2_sc6_out_execute_comment1 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:48{/b}\nyeah!", 2, "#ffffff")
default vig2_sc6_out_execute_comment2 = ChatEntry( False, "{b}bacon8r_6 - 6:48{/b}\nYA", 2, "#ffffff")
default vig2_sc6_out_execute_comment3 = ChatEntry( False, "{b}Coriolis - 6:49{/b}\nOMG", 2, "#ffffff")
default vig2_sc6_out_execute_comment4 = ChatEntry( False, "{b}_lostinmetr0 - 6:49{/b}\nI cant watch!", 2, "#ffffff")
default vig2_sc6_out_execute_comment5 = ChatEntry( False, "{b}shnzi - 6:49{/b}\ngirl WHAT", 2, "#ffffff")
default vig2_sc6_out_execute_comment6 = ChatEntry( False, "{b}PickledDragons - 6:49{/b}\nWOW", 2, "#ffffff")
default vig2_sc6_out_execute_comment7 = ChatEntry( False, "{b}R4dioRobbie - 6:50{/b}\nrip that guy", 2, "#ffffff")
default vig2_sc6_out_execute_comment8 = ChatEntry( False, "{b}turb0g00se - 6:50{/b}\nCOLD", 2, "#ffffff")
default vig2_sc6_out_execute_comment9 = ChatEntry( False, "{b}AFKAngel - 6:50{/b}\n!!!!!!!!!", 2, "#ffffff")
default vig2_sc6_out_execute_comment10 = ChatEntry( False, "{b}shnzi - 6:50{/b}\nNOT THE \"I HAVE KIDS\" CARD", 2, "#ffffff")
default vig2_sc6_out_execute_comment11 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:50{/b}\nno regrets", 2, "#ffffff")
default vig2_sc6_out_execute_comment12 = ChatEntry( False, "{b}R4dioRobbie - 6:50{/b}\ndon't you mean \"no rugrats\" because now the kids don't have a father", 2, "#ffffff")
default vig2_sc6_out_execute_comment13 = ChatEntry( False, "{b}turb0g00se - 6:51{/b}\nBRO HAHA WHAT", 2, "#ffffff")
default vig2_sc6_out_execute_comment14 = ChatEntry( False, "{b}kitcat - 6:52{/b}\ndead man tells no tales...and is no longer a father", 2, "#ffffff")
default vig2_sc6_out_execute_comment15 = ChatEntry( False, "{b}_lostinmetr0 - 6:52{/b}\nLOL we're all awful, aren't we?", 2, "#ffffff")
default vig2_sc6_out_spare_comment1 = ChatEntry( False, "{b}PickledDragons - 6:48{/b}\nlobs grenades and kills all of the staff but the last guy? Nah he's good", 2, "#ffffff")
default vig2_sc6_out_spare_comment2 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:48{/b}\nomg cmon", 2, "#ffffff")
default vig2_sc6_out_spare_comment3 = ChatEntry( False, "{b}turb0g00se - 6:48{/b}\nREGGIEEEEEE", 2, "#ffffff")
default vig2_sc6_out_spare_comment4 = ChatEntry( False, "{b}bacon8r_6 - 6:49{/b}\nHES SO REAL FOR THAT", 2, "#ffffff")
default vig2_sc6_out_spare_comment5 = ChatEntry( False, "{b}kitcat - 6:50{/b}\n\"he didn't need to die\" okay neither did the minimum 4 other people we just blasted", 2, "#ffffff")
default vig2_sc6_out_spare_comment6 = ChatEntry( False, "{b}shnzi - 6:51{/b}\n\"we\"? none of us killed anyone if we played this chapter befr", 2, "#ffffff")
default vig2_sc6_out_spare_comment7 = ChatEntry( False, "{b}_lostinmetr0 - 6:52{/b}\nhey hey - we're all a team now: a chat united in destruction", 2, "#ffffff")

#Comments for Scene 7
default vig2_sc7_comment1 = ChatEntry( False, "{b}AFKAngel - 6:55{/b}\nomg no not the aid shipment", 2, "#ffffff")
default vig2_sc7_comment2 = ChatEntry( False, "{b}turb0g00se - 6:55{/b}\npoor community needing aid vs one robot", 2, "#ffffff")
default vig2_sc7_comment3 = ChatEntry( False, "{b}_lostinmetr0 - 6:56{/b}\nLOL omg true", 2, "#ffffff")
default vig2_sc7_comment4 = ChatEntry( False, "{b}PickledDragons - 6:58{/b}\nagain reginald making sense", 2, "#ffffff")
default vig2_sc7_comment5 = ChatEntry( False, "{b}bacon8r_6 - 6:58{/b}\nmc getting called OUT", 2, "#ffffff")
default vig2_sc7_comment6 = ChatEntry( False, "{b}Coriolis - 6:59{/b}\npoor MAC cant compute", 2, "#ffffff")
default vig2_sc7_comment7 = ChatEntry( False, "{b}kitcat - 7:00{/b}\nhe's just a lil guy doing his best!", 2, "#ffffff")

#Comments for Scene 7 - Marshall
default vig2_sc7_mar_comment1 = ChatEntry( False, "{b}J4MIR0QU4I - 7:02{/b}\nmakes sense", 2, "#ffffff")
default vig2_sc7_mar_comment2 = ChatEntry( False, "{b}_lostinmetr0 - 7:03{/b}\nbut how are we gonna make it out now?", 2, "#ffffff")
default vig2_sc7_mar_comment3 = ChatEntry( False, "{b}turb0g00se - 7:05{/b}\nreginald about to earn his paycheck", 2, "#ffffff")
default vig2_sc7_mar_stun_comment1 = ChatEntry( False, "{b}bacon8r_6 - 7:06{/b}\nrip", 2, "#ffffff")
default vig2_sc7_mar_bribe_comment1 = ChatEntry( False, "{b}Coriolis - 7:06{/b}\nclever!", 2, "#ffffff")
default vig2_sc7_mar_bribe_comment2 = ChatEntry( False, "{b}kitcat - 7:07{/b}\nyeah I stunned him!", 2, "#ffffff")
default vig2_sc7_mar_comment4 = ChatEntry( False, "{b}AFKAngel - 7:08{/b}\nOH COME ON", 2, "#ffffff")
default vig2_sc7_mar_comment5 = ChatEntry( False, "{b}PickledDragons - 7:09{/b}\nCLASSIC paragon game cop out making the good choice have NO consequences", 2, "#ffffff")
default vig2_sc7_mar_comment6 = ChatEntry( False, "{b}R4dioRobbie - 7:10{/b}\ntotally agree", 2, "#ffffff")
default vig2_sc7_mar_comment7 = ChatEntry( False, "{b}Coriolis - 7:10{/b}\nI gotta agree too - was hoping the good choice would at least be interesting consequence-wise", 2, "#ffffff")
default vig2_sc7_mar_comment8 = ChatEntry( False, "{b}turb0g00se - 7:11{/b}\nlets be honest, we all knew this was coming.", 2, "#ffffff")
default vig2_sc7_mar_comment9 = ChatEntry( False, "{b}_lostinmetr0 - 7:14{/b}\nthis team really relies on lucking into helpful people lol", 2, "#ffffff")

#Comments for Scene 7 - Outlaw
default vig2_sc7_out_comment1 = ChatEntry( True, "{b}R4dioRobbie - 7:01{/b}\nWEVE COME THIS FAR", 2, "#ffffff", "vig2_sc7_toofar")
default vig2_sc7_out_comment2_shnzi = ChatEntry( False, "{b}shnzi - 7:03{/b}\nliterally the most black and white decision of the game", 2, "#ffffff")
default vig2_sc7_out_comment2_AFK = ChatEntry( False, "{b}AFKAngel - 7:03{/b}\nliterally the most black and white decision of the game", 2, "#ffffff")
default vig2_sc7_out_comment3 = ChatEntry( False, "{b}kitcat - 7:04{/b}\nand we have shown our blackened heart >:)", 2, "#ffffff")
default vig2_sc7_out_comment4 = ChatEntry( False, "{b}bacon8r_6 - 7:04{/b}\nF", 2, "#ffffff")
default vig2_sc7_out_comment5 = ChatEntry( False, "{b}turb0g00se - 7:05{/b}\nmy condolences but...we doing the bad guy thing", 2, "#ffffff")
default vig2_sc7_out_comment6 = ChatEntry( False, "{b}_lostinmetr0 - 7:05{/b}\nI think youre literally the first person that was like \" nah f those sick people\"", 2, "#ffffff")
default vig2_sc7_out_comment7 = ChatEntry( False, "{b}P0tat0Pr0phet - 7:06{/b}\nLOL you might be right", 2, "#ffffff")
default vig2_sc7_out_comment8 = ChatEntry( False, "{b}PickledDragons - 7:06{/b}\ndude this is awesome", 2, "#ffffff")
default vig2_sc7_out_comment9 = ChatEntry( False, "{b}Coriolis - 7:07{/b}\nawesome?", 2, "#ffffff")
default vig2_sc7_out_comment10 = ChatEntry( False, "{b}PickledDragons - 7:07{/b}\nnonono not that we killed a bunch of sick people", 2, "#ffffff")
default vig2_sc7_out_comment11 = ChatEntry( False, "{b}Coriolis - 7:07{/b}\ngood LOL", 2, "#ffffff")
default vig2_sc7_out_comment12 = ChatEntry( False, "{b}PickledDragons - 7:08{/b}\nI'm just having fun that we're picking things a lot of people don't", 2, "#ffffff")
default vig2_sc7_out_comment13 = ChatEntry( False, "{b}turb0g00se - 7:08{/b}\nsame!!", 2, "#ffffff")
default vig2_sc7_out_comment14 = ChatEntry( False, "{b}Coriolis - 7:08{/b}\nyeah [streamer]'s fun to watch", 2, "#ffffff")
default vig2_sc7_out_comment15 = ChatEntry( False, "{b}J4MIR0QU4I - 7:09{/b}\nyes!", 2, "#ffffff")
default vig2_sc7_out_comment16 = ChatEntry( False, "{b}R4dioRobbie - 7:10{/b}\nLIVE STREAM backwards iS EVIL (maerts) >:)", 2, "#ffffff")
default vig2_sc7_out_comment17 = ChatEntry( False, "{b}turb0g00se - 7:10{/b}\nthat's so corny", 2, "#ffffff")
default vig2_sc7_out_comment18 = ChatEntry( False, "{b}_lostinmetr0 - 7:10{/b}\nno rugrats for real now", 2, "#ffffff")
default vig2_sc7_out_comment19_shnzi = ChatEntry( False, "{b}shnzi - 7:11{/b}\nomg true rip", 2, "#ffffff")
default vig2_sc7_out_comment19_bacon = ChatEntry( False, "{b}bacon8r_6 - 7:11{/b}\nomg true rip", 2, "#ffffff")
default vig2_sc7_out_comment20 = ChatEntry( False, "{b}_lostinmetr0 - 7:12{/b}\nmy adrenaline is so high right now", 2, "#ffffff")
default vig2_sc7_out_comment21 = ChatEntry( False, "{b}kitcat - 7:12{/b}\nSAME", 2, "#ffffff")
default vig2_sc7_out_comment22 = ChatEntry( False, "{b}P0tat0Pr0phet - 7:12{/b}\nlast man standing, you know what to do", 2, "#ffffff")
default vig2_sc7_out_comment23 = ChatEntry( False, "{b}AFKAngel - 7:13{/b}\nGUYS WE CANT", 2, "#ffffff")
default vig2_sc7_out_comment24 = ChatEntry( False, "{b}turb0g00se - 7:13{/b}\nour last shred of dignity", 2, "#ffffff")
default vig2_sc7_out_coerce_comment1 = ChatEntry( False, "{b}_lostinmetr0 - 7:13{/b}\nyeah honestly we've done enough damage to these humanitarians", 2, "#ffffff")
default vig2_sc7_out_coerce_comment2 = ChatEntry( False, "{b}R4dioRobbie - 7:14{/b}\nmmm maybe", 2, "#ffffff")
default vig2_sc7_out_coerce_comment3 = ChatEntry( False, "{b}AFKAngel - 7:14{/b}\nLOL MAYBE?", 2, "#ffffff")
default vig2_sc7_out_coerce_comment4 = ChatEntry( False, "{b}R4dioRobbie - 7:14{/b}\nI'm getting in the outlaw spirit!", 2, "#ffffff")
default vig2_sc7_out_execute_comment1 = ChatEntry( False, "{b}bacon8r_6 - 7:13{/b}\nNO SURVIVORS", 2, "#ffffff")
default vig2_sc7_out_execute_comment2 = ChatEntry( False, "{b}J4MIR0QU4I - 7:13{/b}\nhumanitarians? Not on our watch", 2, "#ffffff")
default vig2_sc7_out_execute_comment3 = ChatEntry( False, "{b}_lostinmetr0 - 7:13{/b}\nwe stand for justice...sort of", 2, "#ffffff")
default vig2_sc7_out_execute_comment4 = ChatEntry( True, "{b}PickledDragons - 7:14{/b}\nChat, time to RIP for our humanitarians", 2, "#ffffff", "vig2_sc7_rips")
default vig2_sc7_out_comment25 = ChatEntry( False, "{b}bacon8r_6 - 7:15{/b}\nAnd there she blows", 2, "#ffffff")
default vig2_sc7_out_comment26 = ChatEntry( False, "{b}J4MIR0QU4I - 7:15{/b}\nLOL omg I feel so bad for laughing", 2, "#ffffff")
default vig2_sc7_out_comment27 = ChatEntry( False, "{b}R4dioRobbie - 7:16{/b}\ncmon Jennica, we're all on board", 2, "#ffffff")
default vig2_sc7_out_comment28 = ChatEntry( False, "{b}turb0g00se - 7:16{/b}\nyeah go team \"dgaf like reginald\"", 2, "#ffffff")

#Comments for Marshall Epilogue
default vig2_epilogue_mar_comment1 = ChatEntry( False, "{b}turb0g00se - 7:15{/b}\nfor all that tension it ended in a low key dull place", 2, "#ffffff")
default vig2_epilogue_mar_comment2 = ChatEntry( False, "{b}Coriolis - 7:15{/b}\nyea the storytelling got a bit dicey at the end there", 2, "#ffffff")
default vig2_epilogue_mar_comment3 = ChatEntry( False, "{b}_lostinmetr0 - 7:16{/b}\nat least we stayed true to ourselves though", 2, "#ffffff")
default vig2_epilogue_mar_comment4 = ChatEntry( False, "{b}kitcat - 7:16{/b}\nanti-hero vibes, but more \"hero\" than \"anti\"", 2, "#ffffff")
default vig2_epilogue_mar_comment5 = ChatEntry( False, "{b}AFKAngel - 7:17{/b}\noh matticus big mad", 2, "#ffffff")
default vig2_epilogue_mar_comment6 = ChatEntry( False, "{b}R4dioRobbie - 7:17{/b}\nat least those sick people aren't the big sad now", 2, "#ffffff")
default vig2_epilogue_mar_comment7 = ChatEntry( False, "{b}turb0g00se - 7:18{/b}\nLOL", 2, "#ffffff") 
default vig2_epilogue_mar_comment8 = ChatEntry( False, "{b}J4MIR0QU4I - 7:18{/b}\nway more chill than last time", 2, "#ffffff")
default vig2_epilogue_mar_comment9 = ChatEntry( False, "{b}Coriolis - 7:19{/b}\nokay guys! Chat next week!", 2, "#ffffff")
default vig2_epilogue_mar_comment10 = ChatEntry( False, "{b}AFKAngel - 7:20{/b}\nyeah sure!", 2, "#ffffff")
default vig2_epilogue_mar_comment11 = ChatEntry( False, "{b}_lostinmetr0 - 7:20{/b}\nhave a great week everyone!", 2, "#ffffff")
default vig2_epilogue_mar_comment12 = ChatEntry( False, "{b}kitcat - 7:20{/b}\ncatch ya on the flip side!", 2, "#ffffff")

#Comments for Outlaw Epilogue
default vig2_epilogue_out_comment1 = ChatEntry( False, "{b}AFKAngel - 7:18{/b}\nwhat a wild ride", 2, "#ffffff")
default vig2_epilogue_out_comment2 = ChatEntry( False, "{b}_lostinmetr0 - 7:18{/b}\nwe'll make matticus indirectly aid in saving the universe", 2, "#ffffff")
default vig2_epilogue_out_comment3 = ChatEntry( False, "{b}kitcat - 7:19{/b}\nmatticus loves Mac too im convinced", 2, "#ffffff")
default vig2_epilogue_out_comment4 = ChatEntry( False, "{b}J4MIR0QU4I - 7:19{/b}\nhow can he not?", 2, "#ffffff")
default vig2_epilogue_out_comment5 = ChatEntry( False, "{b}PickledDragons - 7:19{/b}\nI feel exhausted that was such a roller coaster", 2, "#ffffff")
default vig2_epilogue_out_comment6 = ChatEntry( True, "{b}Coriolis - 7:20{/b}\nyou're telling me! Not how we typically do things at all...right cap?", 2, "#ffffff", "vig2_epilogue_outlaw")
default vig2_epilogue_out_comment7 = ChatEntry( False, "{b}_lostinmetr0 - 7:20{/b}\nbut I had so much fun honestly", 2, "#ffffff")
default vig2_epilogue_out_comment8 = ChatEntry( False, "{b}P0tat0Pr0phet - 7:21{/b}\nyeah this chat is the best yall are too funny", 2, "#ffffff")
default vig2_epilogue_out_comment9 = ChatEntry( False, "{b}turb0g00se - 7:22{/b}\nI hope next week is even more crazy", 2, "#ffffff")
default vig2_epilogue_out_comment10 = ChatEntry( False, "{b}bacon8r_6 - 7:22{/b}\nhard to top murdering a bunch of humanitarians AND annihilating a planet of poor people overrun with plague", 2, "#ffffff")
default vig2_epilogue_out_comment11 = ChatEntry( False, "{b}shnzi - 7:22{/b}\nbro when you say it like that I sorta feel bad", 2, "#ffffff")
default vig2_epilogue_out_comment12 = ChatEntry( False, "{b}R4dioRobbie - 7:23{/b}\nno rugrats!", 2, "#ffffff")
default vig2_epilogue_out_comment13 = ChatEntry( False, "{b}turb0g00se - 7:23{/b}\nLOL", 2, "#ffffff")
default vig2_epilogue_out_comment14 = ChatEntry( False, "{b}shnzi - 7:23{/b}\nyeah true time to channel my inner outlaw and out of sight out of mind it", 2, "#ffffff")
default vig2_epilogue_out_comment15 = ChatEntry( False, "{b}PickledDragons - 7:24{/b}\nplus we get to see where this matticus allyship goes", 2, "#ffffff")
default vig2_epilogue_out_comment16 = ChatEntry( False, "{b}AFKAngel - 7:24{/b}\neven if it goes nowhere, at least we tried?", 2, "#ffffff")
default vig2_epilogue_out_comment17 = ChatEntry( False, "{b}kitcat - 7:25{/b}\nagreed!", 2, "#ffffff")
default vig2_epilogue_out_comment18 = ChatEntry( False, "{b}Coriolis - 7:25{/b}\nfor everyone wanting to see the next stream - we meet at this time every Friday when the new episode drops", 2, "#ffffff")
default vig2_epilogue_out_comment19 = ChatEntry( False, "{b}_lostinmetr0 - 7:26{/b}\noh thanks! I'm gonna send the link to a couple buddies", 2, "#ffffff")
default vig2_epilogue_out_comment20 = ChatEntry( False, "{b}bacon8r_6 - 7:27{/b}\nsame!", 2, "#ffffff")
default vig2_epilogue_out_comment21 = ChatEntry( False, "{b}shnzi - 7:27{/b}\noh my gosh yeah literally had my heart racing", 2, "#ffffff")
default vig2_epilogue_out_comment22 = ChatEntry( False, "{b}AFKAngel - 7:27{/b}\nwe should start a blueit thread or something", 2, "#ffffff")
default vig2_epilogue_out_comment23 = ChatEntry( False, "{b}turb0g00se - 7:27{/b}\nthat's a good idea!", 2, "#ffffff")
default vig2_epilogue_out_comment24 = ChatEntry( False, "{b}PickledDragons - 7:27{/b}\ntotally! we can post our anti-humanitarian agenda there", 2, "#ffffff")
default vig2_epilogue_out_comment25 = ChatEntry( False, "{b}turb0g00se - 7:28{/b}\nLOL >:)", 2, "#ffffff")
default vig2_epilogue_out_comment26 = ChatEntry( False, "{b}shnzi - 7:28{/b}\nhave a great week everyone!", 2, "#ffffff")
default vig2_epilogue_out_comment27 = ChatEntry( False, "{b}_lostinmetr0 - 7:28{/b}\nsee you soon!", 2, "#ffffff")

#Comments for Outlaw Epilogue RIPs
default vig2_epilogue_out_rips1 = ChatEntry( False, "{b}turb0g00se - 7:14{/b}\nRIP", 2, "#ffffff")
default vig2_epilogue_out_rips2 = ChatEntry( False, "{b}AFKAngel - 7:14{/b}\nrip", 2, "#ffffff")
default vig2_epilogue_out_rips3 = ChatEntry( False, "{b}shnzi - 7:14{/b}\nripperoo", 2, "#ffffff")
default vig2_epilogue_out_rips4 = ChatEntry( False, "{b}P0tat0Pr0phet - 7:14{/b}\nFs", 2, "#ffffff")
default vig2_epilogue_out_rips5 = ChatEntry( False, "{b}bacon8r_6 - 7:15{/b}\nrest", 2, "#ffffff")
default vig2_epilogue_out_rips6 = ChatEntry( False, "{b}_lostinmetr0 - 7:15{/b}\nripperoni", 2, "#ffffff")
default vig2_epilogue_out_rips7 = ChatEntry( False, "{b}J4MIR0QU4I - 7:15{/b}\nR I P", 2, "#ffffff")

### Streamer react chats###

default vig2_sc1_reactcomment1 = ChatEntry( False, "{b}turb0g00se - 5:40{/b}\npretty gud. got a pokebowl.", 1, "#ffffff")
default vig2_sc1_reactcomment2 = ChatEntry( False, "{b}turb0g00se - 5:40{/b}\nwe all about trouble!", 1, "#ffffff")
default vig2_sc1_reactcomment3 = ChatEntry( False, "{b}AFKAngel - 5:42{/b}\nhimbo dead sadge.", 1, "#ffffff")
default vig2_sc1_reactcomment4 = ChatEntry( False, "{b}PickledDragons - 5:42{/b}\nbuyers remorse lol", 1, "#ffffff")
default vig2_sc1_reactcomment5 = ChatEntry( False, "{b}kitcat - 5:42{/b}\nyaaah dont mess with MAC!", 1, "#ffffff")
default vig2_sc1_reactcomment6 = ChatEntry( False, "{b}R4dioRobbie - 5:49{/b}\nlooks like a lot!", 1, "#ffffff")
default vig2_sc1_reactcomment7 = ChatEntry( False, "{b}Squeejieboy33 - 5:49{/b}\njennica T_T", 1, "#ffffff")
default vig2_sc1_reactcomment8 = ChatEntry( False, "{b}J4MIR0QU4I - 5:49{/b}\nnooooooo", 1, "#ffffff")

default vig2_sc2_reactcomment1 = ChatEntry( False, "{b}turb0g00se - 5:53{/b}\ndef 10", 1, "#ffffff")
default vig2_sc2_reactcomment2 = ChatEntry( False, "{b}Coriolis - 5:53{/b}\n10 fsho", 1, "#ffffff")
default vig2_sc2_reactcomment3 = ChatEntry( False, "{b}_lostinmetr0 - 5:53{/b}\n8!", 1, "#ffffff")
default vig2_sc2_reactcomment4 = ChatEntry( False, "{b}R4dioRobbie - 5:53{/b}\nNot Ama!!.", 1, "#ffffff")

default vig2_sc2_reactcomment5 = ChatEntry( False, "{b}HYP3RV3N0M - 5:54{/b}\ncutest cargo!", 1, "#ffffff")
default vig2_sc2_reactcomment6 = ChatEntry( False, "{b}AFKAngel - 5:54{/b}\nadorbs package lol", 1, "#ffffff")
default vig2_sc2_reactcomment7 = ChatEntry( False, "{b}kitcat - 5:54{/b}\nhypnotized by the cuteness uwu", 1, "#ffffff")
default vig2_sc2_reactcomment8 = ChatEntry( False, "{b}Squeejieboy33 - 5:54{/b}\ncute robot OP!", 1, "#ffffff")

default vig2_sc2_reactcomment9 = ChatEntry( False, "{b}_lostinmetr0 - 5:55{/b}\neasiest prediction ever LOL", 1, "#ffffff")
default vig2_sc2_reactcomment10 = ChatEntry( False, "{b}turb0g00se - 5:55{/b}\nfr", 1, "#ffffff")
default vig2_sc2_reactcomment11 = ChatEntry( False, "{b}PickledDragons - 5:55{/b}\nthere's always a problem.", 1, "#ffffff")
default vig2_sc2_reactcomment12 = ChatEntry( False, "{b}AFKAngel - 5:55{/b}\nLOL!", 1, "#ffffff")
default vig2_sc2_reactcomment13 = ChatEntry( False, "{b}kitcat - 5:55{/b}\nThe jig is up!", 1, "#ffffff")

default vig2_sc2_reactcomment14 = ChatEntry( False, "{b}_lostinmetr0 - 6:01{/b}\nFamous last words LOL!", 1, "#ffffff")
default vig2_sc2_reactcomment15 = ChatEntry( False, "{b}kitcat - 6:01{/b}\neverythings cool!", 1, "#ffffff")
default vig2_sc2_reactcomment16 = ChatEntry( False, "{b}PickledDragons - 6:01{/b}\ndying together <3", 1, "#ffffff")

default vig2_sc3_reactcomment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:09{/b}\nNever punished never learn!", 1, "#ffffff")
default vig2_sc3_reactcomment2 = ChatEntry( False, "{b}AFKAngel - 6:09{/b}\nfrfr", 1, "#ffffff")
default vig2_sc3_reactcomment3 = ChatEntry( False, "{b}kitcat - 6:09{/b}\nLOL", 1, "#ffffff")
default vig2_sc3_reactcomment4 = ChatEntry( False, "{b}P0tat0Pr0phet - 6:09{/b}\nWay too easy!", 1, "#ffffff")
default vig2_sc3_reactcomment5 = ChatEntry( False, "{b}HYP3RV3N0M - 6:09{/b}\nyah idk", 1, "#ffffff")

default vig2_sc4_reactcomment1 = ChatEntry( False, "{b}AFKAngel - 6:16{/b}\nRoasted.", 1, "#ffffff")
default vig2_sc4_reactcomment2 = ChatEntry( False, "{b}shnzi - 6:17{/b}\nyah i dont trust this guy", 1, "#ffffff")
default vig2_sc4_reactcomment3 = ChatEntry( False, "{b}Coriolis - 6:16{/b}\nlove the his new design too!", 1, "#ffffff")
default vig2_sc4_reactcomment4 = ChatEntry( False, "{b}bacon8r_6 - 6:16{/b}\nwooo team chaos!", 1, "#ffffff")
default vig2_sc4_reactcomment5 = ChatEntry( False, "{b}turb0g00se - 6:17{/b}\nso in for being bad.", 1, "#ffffff")

default vig2_sc4_reactcomment6 = ChatEntry( False, "{b}PickledDragons - 6:24{/b}\nI mean you think the mob boss does favours lol", 1, "#ffffff")
default vig2_sc4_reactcomment7 = ChatEntry( False, "{b}AFKAngel - 6:24{/b}\nfr. <3", 1, "#ffffff")
default vig2_sc4_reactcomment8 = ChatEntry( False, "{b}kitcat - 6:24{/b}\nlol lemme just risk myself for nothing.", 1, "#ffffff")
default vig2_sc4_reactcomment9 = ChatEntry( False, "{b}turb0g00se - 6:24{/b}\nwe are so back!", 1, "#ffffff")

default vig2_sc5_reactcomment1 = ChatEntry( False, "{b}kitcat - 6:34{/b}\ndont be a bad robo-parent lol", 1, "#ffffff")
default vig2_sc5_reactcomment2 = ChatEntry( False, "{b}shnzi - 6:34{/b}\nyah hes already repeating skeeve", 1, "#ffffff")
default vig2_sc5_reactcomment3 = ChatEntry( False, "{b}kitcat - 6:34{/b}\nlil bot is learning!", 1, "#ffffff")
default vig2_sc5_reactcomment4 = ChatEntry( False, "{b}kitcat - 6:34{/b}\nnooooo MAC!", 1, "#ffffff")
default vig2_sc5_reactcomment5 = ChatEntry( False, "{b}_lostinmetr0 - 6:34{/b}\nShield MAC's pure eyes!", 1, "#ffffff")

default vig2_sc6_out_reactcomment1 = ChatEntry( False, "{b}turb0g00se - 6:52{/b}\nwhole lotta murder!", 1, "#ffffff")
default vig2_sc6_out_reactcomment2 = ChatEntry( False, "{b}AFKAngel - 6:52{/b}\nmoze is tryna do better lol", 1, "#ffffff")
default vig2_sc6_out_reactcomment3 = ChatEntry( False, "{b}kitcat - 6:52{/b}\ngotta do what ya gotta do.", 1, "#ffffff")
default vig2_sc6_out_reactcomment4 = ChatEntry( False, "{b}HYP3RV3N0M - 6:52{/b}\nlol", 1, "#ffffff")

default vig2_sc6_mar_reactcomment1 = ChatEntry( False, "{b}_lostinmetr0 - 6:51{/b}\nDamn yeah, kinda underwhelming.", 1, "#ffffff")
default vig2_sc6_mar_reactcomment2 = ChatEntry( False, "{b}PickledDragons - 6:51{/b}\nim whelmed.", 1, "#ffffff")
default vig2_sc6_mar_reactcomment3 = ChatEntry( False, "{b}PickledDragons - 6:51{/b}\nmost boring strat lol", 1, "#ffffff")
default vig2_sc6_mar_reactcomment4 = ChatEntry( False, "{b}PickledDragons - 6:51{/b}\nleaving a lot of loose ends lol", 1, "#ffffff")

default vig2_sc7_reactcomment1 = ChatEntry( False, "{b}kitcat - 6:58{/b}\nmoze gettin called out!", 1, "#ffffff")
default vig2_sc7_reactcomment2 = ChatEntry( False, "{b}AFKAngel - 6:58{/b}\ndamn straight!", 1, "#ffffff")
default vig2_sc7_reactcomment3 = ChatEntry( False, "{b}_lostinmetr0 - 6:58{/b}\nI mean its all a matter of degrees.", 1, "#ffffff")
default vig2_sc7_reactcomment4 = ChatEntry( False, "{b}HYP3RV3N0M - 6:58{/b}\nfr", 1, "#ffffff")

default vig2_sc8_out_reactcomment1 = ChatEntry( False, "{b}PickledDragons - 7:14{/b}\nwooooo team chaos!", 1, "#ffffff")
default vig2_sc8_out_reactcomment2 = ChatEntry( False, "{b}P0tat0Pr0phet - 7:14{/b}\nmakes sense", 1, "#ffffff")
default vig2_sc8_out_reactcomment3 = ChatEntry( False, "{b}turb0g00se - 7:14{/b}\ndaaaaaaaaaaamn", 1, "#ffffff")
default vig2_sc8_out_reactcomment4 = ChatEntry( False, "{b}AFKAngel - 7:14{/b}\nwow crazy!", 1, "#ffffff")
default vig2_sc8_out_reactcomment5 = ChatEntry( False, "{b}HYP3RV3N0M - 7:14{/b}\n[streamer]'s doing some evil shit!", 1, "#ffffff")
default vig2_sc8_out_reactcomment6 = ChatEntry( False, "{b}PickledDragons - 7:14{/b}\nits good to be bad!", 1, "#ffffff")

default vig2_sc8_out_reactcomment7 = ChatEntry( False, "{b}kitcat - 7:16{/b}\neeeeh shell get over it.", 1, "#ffffff")
default vig2_sc8_out_reactcomment8 = ChatEntry( False, "{b}J4MIR0QU4I - 7:16{/b}\nye prolly pissed her off", 1, "#ffffff")
default vig2_sc8_out_reactcomment9 = ChatEntry( False, "{b}Squeejieboy33 - 7:16{/b}\nnooooo Jenn T_T!", 1, "#ffffff")
default vig2_sc8_out_reactcomment10 = ChatEntry( False, "{b}PickledDragons - 7:16{/b}\nno such thing as too much!", 1, "#ffffff")
default vig2_sc8_out_reactcomment11 = ChatEntry( False, "{b}Coriolis - 7:16{/b}\nya probably", 1, "#ffffff")
default vig2_sc8_out_reactcomment12 = ChatEntry( False, "{b}_lostinmetr0 - 7:16{/b}\nMaybe way too much lol", 1, "#ffffff")
default vig2_sc8_out_reactcomment13 = ChatEntry( False, "{b}HYP3RV3N0M - 7:16{/b}\nwow brutal.", 1, "#ffffff")
default vig2_sc8_out_reactcomment14 = ChatEntry( False, "{b}PickledDragons - 7:16{/b}\nget rekt villagers!", 1, "#ffffff")
default vig2_sc8_out_reactcomment15 = ChatEntry( False, "{b}shnzi - 7:16{/b}\nlol, lmao even.", 1, "#ffffff")
default vig2_sc8_out_reactcomment16 = ChatEntry( False, "{b}R4dioRobbie - 7:16{/b}\nno rugrats fr this time lol", 1, "#ffffff")

default vig2_sc9_out_reactcomment1 = ChatEntry( False, "{b}AFKAngel - 7:22{/b}\nhope we get a shot", 1, "#ffffff")
default vig2_sc9_out_reactcomment2 = ChatEntry( False, "{b}shnzi - 7:22{/b}\nhe deserves worse!", 1, "#ffffff")
default vig2_sc9_out_reactcomment3 = ChatEntry( False, "{b}HYP3RV3N0M - 7:22{/b}\ndamn [streamer]'s really getting into outlaw!", 1, "#ffffff")
default vig2_sc9_out_reactcomment4 = ChatEntry( False, "{b}turb0g00se - 7:22{/b}\nmob boss route lol", 1, "#ffffff")
default vig2_sc9_out_reactcomment5 = ChatEntry( False, "{b}J4MIR0QU4I - 7:22{/b}\nyah ppl miss so much.", 1, "#ffffff")
default vig2_sc9_out_reactcomment6 = ChatEntry( False, "{b}PickledDragons - 7:22{/b}\noutlawlife!", 1, "#ffffff")

default vig2_sc8_mar_reactcomment1 = ChatEntry( False, "{b}turb0g00se - 7:05{/b}\naddem to the pile!", 1, "#ffffff")
default vig2_sc8_mar_reactcomment2 = ChatEntry( False, "{b}shnzi - 7:05{/b}\nMoze just loves killin!", 1, "#ffffff")
default vig2_sc8_mar_reactcomment3 = ChatEntry( False, "{b}_lostinmetr0 - 7:05{/b}\ncant be so easy lol", 1, "#ffffff")
default vig2_sc8_mar_reactcomment4 = ChatEntry( False, "{b}P0tat0Pr0phet - 7:05{/b}\nhenchman so loyal", 1, "#ffffff")
default vig2_sc8_mar_reactcomment5 = ChatEntry( False, "{b}Squeejieboy33 - 7:05{/b}\nno chance.", 1, "#ffffff")
default vig2_sc8_mar_reactcomment6 = ChatEntry( False, "{b}PickledDragons - 7:05{/b}\nbribe again wow", 1, "#ffffff")


default vig2_sc8_mar_reactcomment7 = ChatEntry( False, "{b}PickledDragons - 7:06{/b}\nsigh lol", 1, "#ffffff")
default vig2_sc8_mar_reactcomment8 = ChatEntry( False, "{b}R4dioRobbie - 7:06{/b}\nshoulda killed him lol", 1, "#ffffff")
default vig2_sc8_mar_reactcomment9 = ChatEntry( False, "{b}Squeejieboy33 - 7:06{/b}\nlol Jenn is ruthless!", 1, "#ffffff")
default vig2_sc8_mar_reactcomment10 = ChatEntry( False, "{b}HYP3RV3N0M - 7:06{/b}\nHell yah!", 1, "#ffffff")
default vig2_sc8_mar_reactcomment11 = ChatEntry( False, "{b}turb0g00se - 7:06{/b}\ngood but not too good lol", 1, "#ffffff")

default vig2_sc8_mar_reactcomment12 = ChatEntry( False, "{b}AFKAngel - 7:07{/b}\nMoney is the best weapon lol", 1, "#ffffff")
default vig2_sc8_mar_reactcomment13 = ChatEntry( False, "{b}PickledDragons - 7:07{/b}\ntoo easy.", 1, "#ffffff")
default vig2_sc8_mar_reactcomment14 = ChatEntry( False, "{b}bacon8r_6 - 7:07{/b}\nbribe is like the default.", 1, "#ffffff")
default vig2_sc8_mar_reactcomment15 = ChatEntry( False, "{b}turb0g00se - 7:07{/b}\nyah fr", 1, "#ffffff")
default vig2_sc8_mar_reactcomment16 = ChatEntry( False, "{b}bacon8r_6 - 7:07{/b}\nnah reggies so cool", 1, "#ffffff")
default vig2_sc8_mar_reactcomment17 = ChatEntry( False, "{b}PickledDragons - 7:07{/b}\nhow is the oakley so flush with cash lol", 1, "#ffffff")

default vig2_sc9_mar_reactcomment1 = ChatEntry( False, "{b}PickledDragons - 7:15{/b}\nlol forger pops up to bail you out", 1, "#ffffff")
default vig2_sc9_mar_reactcomment2 = ChatEntry( False, "{b}_lostinmetr0 - 7:15{/b}\nwaaaaaay too convenient", 1, "#ffffff")
default vig2_sc9_mar_reactcomment3 = ChatEntry( False, "{b}kitcat - 7:15{/b}\nbest of both worlds!", 1, "#ffffff")
default vig2_sc9_mar_reactcomment4 = ChatEntry( False, "{b}turb0g00se - 7:15{/b}\nbut matticus!", 1, "#ffffff")
default vig2_sc9_mar_reactcomment5 = ChatEntry( False, "{b}bacon8r_6 - 7:15{/b}\nooof feeling bad about not killin?", 1, "#ffffff")
default vig2_sc9_mar_reactcomment6 = ChatEntry( False, "{b}R4dioRobbie - 7:15{/b}\nlol", 1, "#ffffff")



######Setting up Bluit Threads###########
default vig2_bThread1 = bThread( 1, "vig2_blueit_allistarthread", "images/socials/bThread_v2_allistar.png") #tag, target, image
default vig2_bThread2 = bThread( 1, "vig2_blueit_matticusthread", "images/socials/bThread_v2_matticusDesign.png")
default vig2_bThread3 = bThread( 1, "vig2_blueit_copoutthread", "images/socials/bThread_v2_copout.png")
default vig2_bThread4 = bThread( 1, "vig2_blueit_stealththread", "images/socials/bThread_v2_muchStealth.png")











###################### OLD COMMENTS FROM PROTOTYPING########################


#comments for decision 2
default pdLovesChaos = ChatEntry (False, "{b}PickledDragons - {/b}\nchaos chaos chaos chaos", 0, "#000000ff")
default kkMac = ChatEntry (False, "{b}KitKat - {/b}\nOh no Mac!", 0, "#000000ff")
#comments for outlaw decision 2
default pdOutlawD2 = ChatEntry (False, "{b}PickledDragons - {/b}\nCHAOS CHAOS CHAOS", 0, "#000000ff")
default csOutlawD2 = ChatEntry(True, "{b}Coriolis - {/b}\nbahahaha just like my DnD group's stealth rols", 0, "#000000ff", "CoriolisTalksDnDOutlaw")

#comments for marshal decision 2
default csMarshalD2 = ChatEntry(True, "{b}Coriolis - {/b}\nJennica the top-tier support character of the DnD party", 0, "#000000ff", "CoriolisTalksDnDMarshal")
default kkMarshalD2 = ChatEntry(False, "{b}KitKat - {/b}\nAwww I wanted to see what Teresa had up her sleeve", 0, "#000000ff" )

#comments for CoriolisDnD talk
default csDnDvg2 = ChatEntry (False, "{b}Coriolis - {/b}\nnooooo hit her up again, make it happen!", 0, "#000000ff")
default csDnD2vg2 = ChatEntry (False, "{b}Coriolis - {/b}\nsame! I go cleric a lot of the time, though I typically spec it to be effective in combat too", 0, "#000000ff" )
default kkDnDvg2 = ChatEntry (True, "{b}KitKat - {/b}\nWhat class do you think [streamer] would run?", 0, "#000000ff", "DnDClassTalk")
default kkDnDvg2play = ChatEntry (True, "{b}KitKat - {/b}\nWhat class do you think [streamer] runs?", 0, "#000000ff", "DnDClassTalkplay")
default pdDnDvg2 = ChatEntry (False, "{b}PickledDragons - {/b}\nI'm seeing Paladin for some reason personally", 0, "#000000ff")
default pdDnD2vg2 = ChatEntry (False, "{b}PickledDragons - {/b}\nCalled it!", 0, "#000000ff")
