###Comments vig4_sc1_1 - Teresa upgrading MAC
default vig4_sc1_comment1 = ChatEntry( False, "{b}turb0g00se - 6:01{/b}\nHere we go", 4, "#ffffff")
default vig4_sc1_comment2 = ChatEntry( False, "{b}Coriolis - 6:02{/b}\nTonight's the night!", 4, "#ffffff")
default vig4_sc1_comment3 = ChatEntry( False, "{b}kitcat - 6:02{/b}\nTime for the exciting conclusion!", 4, "#ffffff")
default vig4_sc1_comment4 = ChatEntry( False, "{b}_lostinmetr0 - 6:02{/b}\nWe are so back!", 4, "#ffffff")
default vig4_sc1_comment5 = ChatEntry( True, "{b}pickledDragons - 6:03{/b}\nSo do we think Moze cured her PTSD or are we in for some more hallucinations?", 4, "#ffffff", "vig4_sc1_pdParanoia")
default vig4_sc1_comment6 = ChatEntry(False, "{b}AFKAngel - 6:04{/b}\nMe too, my parents try to reboot my drivers aaallll the time", 4, "#ffffff")
default vig4_sc1_comment7 = ChatEntry(False, "{b}R4dioRobbie - 6:04{/b}\nIt's the thermal paste for me", 4, "#ffffff")
default vig4_sc1_comment8 = ChatEntry(False, "{b}J4MIR0QU4I - 6:04{/b}\n...wut", 4, "#ffffff")
default vig4_sc1_comment9 = ChatEntry(False, "{b}kitcat - 6:05{/b}\nupgrades for the boi! Wooo!", 4, "#ffffff")
default vig4_sc1_comment10 = ChatEntry(False, "{b}marxky8 - 6:05{/b}\noop, a lil sassy now, are we?", 4, "#ffffff")
default vig4_sc1_comment9alt = ChatEntry(False, "{b}kitcat - 6:05{/b}\nWait no! What are they up to!", 4, "#ffffff" )
default vig4_sc1_comment10alt = ChatEntry(False, "{b}turb0g00se - 6:05{/b}\nNo time, Moze on a mission", 4, "#ffffff")
default vig4_sc1_comment11 = ChatEntry(False, "{b}kitcat - 6:06{/b}\ncallback! lil guy remembers what you done", 4, "#ffffff")
default vig4_sc1_comment12 = ChatEntry(False, "{b}jerrybean784 - 6:06{/b}\ngotta learn 'em yung", 4, "#ffffff")
default vig4_sc1_comment13 = ChatEntry(False, "{b}kitcat - 6:06{/b}\nbahaha", 4, "#ffffff")
default vig4_sc1_comment14 = ChatEntry(False, "{b}Coriolis - 6:06{/b}\aaahh the kid's got jokes now", 4, "#ffffff")

###Comments vig4_sc1_2 - Crew debriefing mission
default vig4_sc1_2_comment1 = ChatEntry(False, "{b}pickledDragons - 6:07{/b}\nIt's so much more chill than the start of the last episode", 4, "#ffffff")
default vig4_sc1_2_comment2 = ChatEntry(False, "{b}llamabama22 - 6:07{/b}\nclassic calm before the storm", 4, "#ffffff")
default vig4_sc1_2_comment3 = ChatEntry(False, "{b}_lostinmetr0 - 6:07{/b}\nsteam: fully blown off. Thanks Akar", 4, "#ffffff")
default vig4_sc1_2_comment4 = ChatEntry(False, "{b}J4MIR0QU4I - 6:08{/b}\nhonestly, I ship these two more than with the cap", 4, "#ffffff")
default vig4_sc1_2_comment5 = ChatEntry(False, "{b}marxky8 - 6:08{/b}\nfr Jeresa hive stand up!", 4, "#ffffff")
default vig4_sc1_2_comment6 = ChatEntry(False, "{b}AFKAngel - 6:08{/b}\ndon't worry, they got the thermal paste replacements", 4, "#ffffff")
default vig4_sc1_2_comment7 = ChatEntry(False, "{b}turb0g00se - 6:09{/b}\nTiny rock in the middle of nowhere? Perfect spot for some crimes!", 4, "#ffffff")
default vig4_sc1_2_comment8 = ChatEntry(False, "{b}R4dioRobbie - 6:09{/b}\nagainst humanity?", 4, "#ffffff")
default vig4_sc1_2_comment9 = ChatEntry(False, "{b}turb0g00se - 6:09{/b}\nWe'll see when we get there won't we ;)", 4, "#ffffff")
default vig4_sc1_2_comment10 = ChatEntry(False, "{b}pickledDragons - 6:10{/b}\nWe've heard very little about the Alliance this game. Think they'll come up here at the end?", 4, "#ffffff")
default vig4_sc1_2_comment11 = ChatEntry(False, "{b}llamabama22 - 6:10{/b}\nsus", 4, "#ffffff")
default vig4_sc1_2_comment12 = ChatEntry(False, "{b}jerrybean784 - 6:10{/b}\nsus", 4, "#ffffff")
default vig4_sc1_2_comment13 = ChatEntry(False, "{b}AFKAngel - 6:10{/b}\n very sus", 4, "#ffffff")
default vig4_sc1_2_comment14 = ChatEntry(False, "{b}bacon8r_6 - 6:10{/b}\nsus", 4, "#ffffff")
default vig4_sc1_2_comment15 = ChatEntry(False, "{b}pickledDragons - 6:11{/b}\nhell yeah, MAC's down with the revolution!", 4, "#ffffff")
default vig4_sc1_2_comment16 = ChatEntry(False, "{b}kitcat - 6:11{/b}\nAll grown up and sticking it to the establishment", 4, "#ffffff")
default vig4_sc1_2_comment17 = ChatEntry(False, "{b}Coriolis - 6:11{/b}\nLove to see the ensign learning from the Cap!", 4, "#ffffff")
default vig4_sc1_2_comment18 = ChatEntry(False, "{b}R4dioRobbie - 6:12{/b}\nthis Jeresa ship seems miighty appealing", 4, "#ffffff")
default vig4_sc1_2_comment19 = ChatEntry(False, "{b}kitcat - 6:12{/b}\nnah team Moresa is the best", 4, "#ffffff")
default vig4_sc1_2_comment20 = ChatEntry(True, "{b}Coriolis - 6:12{/b}\nIt's all about Jennoze, right, Cap?", 4, "#ffffff")
default vig4_sc1_2_comment21 = ChatEntry(False, "{b}bacon8r_6 - 6:13{/b}\ncause that went great the last time he tried it", 4, "#ffffff")
default vig4_sc1_2_comment22 = ChatEntry(False, "{b}pickledDragons - 6:13{/b}\nHey he actually managed to hold his own. That scene with the gun on the balcony?", 4, "#ffffff")
default vig4_sc1_2_comment23 = ChatEntry(False, "{b}kitcat - 6:14{/b}\noof brutal. Like it makes sense, but why you gotta say it like that", 4, "#ffffff")
default vig4_sc1_2_comment24 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:15{/b}\nno way MAC stays on the ship. Calling it rn", 4, "#ffffff")
default vig4_sc1_2_comment25 = ChatEntry(False, "{b}turb0g00se - 6:15{/b}\nYoooo POTATO! Thought you had class, was worried you weren't gonna make it", 4, "#ffffff")
default vig4_sc1_2_comment26 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:15{/b}\nI am in class lmao streaming in on my phone XD", 4, "#ffffff")

###Comments Vig4_sc2_1 - Entering Polaris
default vig4_sc2_1_comment1 = ChatEntry (True, "{b}kitcat - 6:16{/b}\nSo any predictions on where the story's gonna go [username]?", 4, "#ffffff", "vig4_sc1_kcPrediction")
default vig4_sc2_1_comment2 = ChatEntry (False, "{b}Coriolis - 6:17{/b}\nTeresa always calm", 4, "#ffffff")
default vig4_sc2_1_comment3 = ChatEntry (False, "{b}bacon8r_6 - 6:17{/b}\nwho the hell is this rube?", 4, "#ffffff")
default vig4_sc2_1_comment4 = ChatEntry (False, "{b}xXpearlXx - 6:18{/b}\nBC scum FOR SURE", 4, "#ffffff")
default vig4_sc2_1_comment5 = ChatEntry (False, "{b}_lostinmetr0 - 6:18{/b}\nmaybe he's just a friendly guy?", 4, "#ffffff")
default vig4_sc2_1_comment6 = ChatEntry (False, "{b}R4dioRobbie - 6:18{/b}\nif I had a nickel for every time someone wanted me to see their 'star shower'", 4, "#ffffff")
default vig4_sc2_1_comment7 = ChatEntry (False, "{b}bacon8r_6 - 6:18{/b}\nZAP", 4, "#ffffff")
default vig4_sc2_1_comment8 = ChatEntry (True, "{b}R4dioRobbie - 6:18{/b}\nRUBE", 4, "#ffffff", "vig4_sc2_rube")
default vig4_sc2_1_comment9 = ChatEntry (False, "{b}J4MIR0QU4I - 6:18{/b}\RUBES", 4, "#ffffff")
default vig4_sc2_1_comment10 = ChatEntry (False, "{b}turb0g00se - 6:18{/b}\nRUBY!", 4, "#ffffff")
default vig4_sc2_1_comment11 = ChatEntry (False, "{b}llamabama22 - 6:18{/b}\nRUBIO!", 4, "#ffffff")
default vig4_sc2_1_comment12 = ChatEntry (False, "{b}AFKAngel - 6:18{/b}\nthis man never set foot on a spaceship in his life", 4, "#ffffff")
default vig4_sc2_1_comment13 = ChatEntry (False, "{b}Coriolis - 6:18{/b}\ndefo not BC tho", 4, "#ffffff")
default vig4_sc2_1_comment14 = ChatEntry (False, "{b}jerrybean784 - 6:18{/b}\nhey evil corporations need their incompetent bureaucrats too", 4, "#ffffff")
default vig4_sc2_1_comment15 = ChatEntry (False, "{b}kitcat - 6:18{/b}\nawww I wanted to see Teresa get in the mix", 4, "#ffffff")
default vig4_sc2_1_comment16 = ChatEntry (False, "{b}_lostinmetr0 - 6:18{/b}\nProbably the right call though, no?", 4, "#ffffff")
default vig4_sc2_1_comment17 = ChatEntry (False, "{b}pickledDragons - 6:18{/b}\nThey are flying blind so it's definitely safer...bit less fun tho lol", 4, "#ffffff")

###Comments for vig4_sc2_2 general - Dealing with the Townsperson
default vig4_sc2_2_comment1 = ChatEntry(False, "{b}pickledDragons - 6:21{/b}\nnow {i}that{/i} is sus", 4, "#ffffff")
default vig4_sc2_2_comment2 = ChatEntry(False, "{b}Coriolis - 6:21{/b}\nYeah that is not a good sign my friends", 4, "#ffffff")
default vig4_sc2_2_comment3 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:21{/b}\nScrew it, burn it to the ground, can't trust anyone", 4, "#ffffff")
default vig4_sc2_2_comment4 = ChatEntry(False, "{b}marxky8 - 6:20{/b}\nptsd's a pain, ain't it", 4, "#ffffff")

###Comments Vig4_sc2_2_solo - Townsperson was stunned
default vig4_sc2_solo_comment1 = ChatEntry(False, "{b}_lostinmetr0 - 6:20{/b}\nYou know Jenn's outfit would slay", 4, "#ffffff")
default vig4_sc2_solo_comment2 = ChatEntry(False, "{b}jerrybean784 - 6:20{/b}\nCan't blame 'em, the Vineyard was whaaaaaaack", 4, "#ffffff")

###Comments Vig4_sc2_2_accompanied - Townsperson leads you into Polaris
default vig4_sc2_accompanied_comment1 = ChatEntry(False, "{b}bacon8r_6 - 6:18{/b}\nOh no now we're stuck with the rube!", 4, "#ffffff")
default vig4_sc2_accompanied_comment3 = ChatEntry(False, "{b}AFKAngel - 6:20{/b}\nThere we go, rube lost", 4, "#ffffff")
default vig4_sc2_accompanied_comment4 = ChatEntry(False, "{b}turb0g00se - 6:21{/b}\nI guess he wasn't a bad dude. Maybe it was good we didn't stun him", 4, "#ffffff")

###Comments Vig4_sc2_3 - Discussing MAC's vocabulary
default vig4_sc2_3_comment1 = ChatEntry(False, "{b}Coriolis - 6:22{/b}\nMama and Mom talking about their son", 4, "#ffffff")
default vig4_sc2_3_comment2 = ChatEntry(False, "{b}kitcat - 6:23{/b}\nGotta make sure he grows up right. Not too much time on the internet", 4, "#ffffff")
default vig4_sc2_3_comment3 = ChatEntry(False, "{b}turb0g00se - 6:23{/b}\nNah, internet is a great place to learn!", 4, "#ffffff")
default vig4_sc2_3_comment4 = ChatEntry(False, "{b}_lostinmetr0 - 6:23{/b}\nomg absentee mother?", 4, "#ffffff")
default vig4_sc2_3_comment5 = ChatEntry(False, "{b}marxky8 - 6:23{/b}\nlike how do you miss that", 4, "#ffffff")
default vig4_sc2_3_comment6 = ChatEntry(False, "{b}R4dioRobbie - 6:23{/b}\nYeah speech patterns...ALSO THE KID PICKED UP A DAMN GUN!", 4, "#ffffff")
default vig4_sc2_3_comment7 = ChatEntry(False, "{b}marxky8 - 6:23{/b}\nGotta love some attentive parenting from the mothers", 4, "#ffffff")
default vig4_sc2_3_comment8 = ChatEntry(False, "{b}llamabama22 - 6:23{/b}\nFortunately, we're almost there", 4, "#ffffff")
default vig4_sc2_3_comment9 = ChatEntry(False, "{b}llamabama22 - 6:23{/b}\nAnd nothing eeeever goes wrong in the third act climax", 4, "#ffffff")
default vig4_sc2_3_comment10 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:23{/b}\nNever", 4, "#ffffff")
default vig4_sc2_3_comment11 = ChatEntry(False, "{b}xXpearlXx - 6:23{/b}\nI mean, a little authoritarian, Moze, but I could see how you'd focus on that", 4, "#ffffff")
default vig4_sc2_3_comment12 = ChatEntry(False, "{b}bacon8r_6 - 6:25{/b}\nI got trap for sure. Any bets?", 4, "#ffffff")
default vig4_sc2_3_comment13 = ChatEntry(False, "{b}turb0g00se - 6:25{/b}\nI'm gonna go with no, actually", 4, "#ffffff")
default vig4_sc2_3_comment14 = ChatEntry(False, "{b}marxky8 - 6:25{/b}\ndefo trap", 4, "#ffffff")
default vig4_sc2_3_comment15 = ChatEntry(False, "{b}pickledDragons - 6:25{/b}\nidk about that. How can you trust these people?", 4, "#ffffff")
default vig4_sc3_3_comment16 = ChatEntry(False, "{b}Coriolis - 6:25{/b}\nSounds like an Outlaw's perspective", 4, "#ffffff")
default vig4_sc2_3_comment17 = ChatEntry(False, "{b}Coriolis - 6:25{/b}\nSeriously? I mean this is {i}the mission{/i}. Just be straight with the people", 4, "#ffffff")
default vig4_sc2_3_comment18 = ChatEntry(False, "{b}pickledDragons - 6:26{/b}\nIf ya wanna be Marshal", 4, "#ffffff")

###Comments vig4_sc2_4 - Meeting Coil
default vig4_sc2_4_comment1 = ChatEntry(False, "{b}llamabama22 - 6:26{/b}\nFather?", 4, "#ffffff")
default vig4_sc2_4_comment2 = ChatEntry(False, "{b}jerrybean784 - 6:26{/b}\nOf course it's some engineer guy", 4, "#ffffff")
default vig4_sc2_4_comment3 = ChatEntry(False, "{b}kitcat - 6:26{/b}\nrude", 4, "#ffffff")
default vig4_sc2_4_comment4 = ChatEntry(False, "{b}_lostinmetr0 - 6:26{/b}\nWell that's not a friendly way to say hello", 4, "#ffffff")
default vig4_sc2_4_comment5 = ChatEntry(False, "{b}J4MIR0QU4I - 6:27{/b}\nnaahhh I don't trust this old dude", 4, "#ffffff")
default vig4_sc2_4_comment6 = ChatEntry(False, "{b}pickledDragons - 6:27{/b}\nCameras. Maybe he controls them?", 4, "#ffffff")
default vig4_sc2_4_comment7 = ChatEntry(False, "{b}AFKAngel - 6:27{/b}\nHey, he deserved it", 4, "#ffffff")
default vig4_sc2_4_comment8 = ChatEntry(False, "{b}AFKAngel - 6:27{/b}\nTravelers who ditch annoying locals, thank you", 4, "#ffffff")
default vig4_sc2_4_comment9 = ChatEntry(False, "{b}R4dioRobbie - 6:28{/b}\nThat dirt tho", 4, "#ffffff")
default vig4_sc2_4_comment10 = ChatEntry(False, "{b}marxky8 - 6:28{/b}\npristine soilage", 4, "#ffffff")
default vig4_sc2_4_comment11 = ChatEntry(False, "{b}turb0g00se - 6:28{/b}\nOooh that sounded like a threat to me!", 4, "#ffffff")
default vig4_sc2_4_comment12 = ChatEntry(False, "{b}bacon8r_6 - 6:28{/b}\nTiem to beat up an old man?", 4, "#ffffff")
default vig4_sc2_4_comment13 = ChatEntry(False, "{b}llamabama22 - 6:28{/b}\nBut he's padre!", 4, "#ffffff")
default vig4_sc2_4_comment14 = ChatEntry(False, "{b}llamabama22 - 6:29{/b}\nOk nope, never mind. Waste grandpa's ass", 4, "#ffffff")
default vig4_sc2_4_comment15 = ChatEntry(False, "{b}kitcat - 6:29{/b}\nYeah Teresa, you tell him!", 4, "#ffffff")
default vig4_sc2_4_comment16 = ChatEntry(False, "{b}pickledDragons - 6:29{/b}\nRead her to filth!", 4, "#ffffff")
default vig4_sc2_4_comment17 = ChatEntry(False, "{b}AFKAngel - 6:30{/b}\nWho's this!?", 4, "#ffffff")
default vig4_sc2_4_comment18 = ChatEntry(False, "{b}_lostinmetr0 - 6:30{/b}\nCool design!", 4, "#ffffff")
default vig4_sc2_4_comment19 = ChatEntry(False, "{b}bacon8r_6 - 6:30{/b}\nTime to beat up an old man + shoot a child??", 4, "#ffffff")
default vig4_sc2_4_comment20 = ChatEntry(False, "{b}Coriolis - 6:30{/b}\nThis is feeling less and less like a trap imo", 4, "#ffffff")
default vig4_sc2_4_comment21 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:30{/b}\nwdym they literally pulled guns on us", 4, "#ffffff")
default vig4_sc2_4_comment22 = ChatEntry(False, "{b}_lostinmetr0 - 6:30{/b}\nI meant like a BC thing", 4, "#ffffff")
default vig4_sc2_4_comment23 = ChatEntry(False, "{b}llamabama22 - 6:31{/b}\nPadre's back", 4, "#ffffff")
default vig4_sc2_4_comment24 = ChatEntry(False, "{b}J4MIR0QU4I - 6:31{/b}\nseek help", 4, "#ffffff")
default vig4_sc2_4_comment25 = ChatEntry(False, "{b}pickledDragons - 6:30{/b}\nOoh yeah let's show him how we do, Cap", 4, "#ffffff")
default vig4_sc2_4_comment26 = ChatEntry(False, "{b}marxky8 - 6:31{/b}\nGrandpa chilling in his shop. Moze: not on my watch", 4, "#ffffff")
default vig4_sc2_4_comment27 = ChatEntry(False, "{b}J4MIR0QU4I - 6:31{/b}\nThis grandpa's got some mind game shit, I don't like it", 4, "#ffffff")
default vig4_sc2_4_comment28 = ChatEntry(False, "{b}_lostinmetr0 - 6:30{/b}\ntbf we did our own bit of antagonizing", 4, "#ffffff")
default vig4_sc2_4_comment29 = ChatEntry(False, "{b}R4dioRobbie - 6:31{/b}\nTrue...but we're more fun XD", 4, "#ffffff")
default vig4_sc2_4_comment30 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:32{/b}\Called it! MAC is op for real now!", 4, "#ffffff")
default vig4_sc2_4_comment31 = ChatEntry(False, "{b}kitcat - 6:32{/b}\nAnd he's got one liners!", 4, "#ffffff")
default vig4_sc2_4_comment32 = ChatEntry(False, "{b}xXpearlXx - 6:32{/b}\nMommy takes her eyes off the kid for one second and he's off to commit crimes", 4, "#ffffff")
default vig4_sc2_4_comment33 = ChatEntry(False, "{b}pickledDragons - 6:32{/b}\nThey grow up so fast", 4, "#ffffff")
default vig4_sc2_4_comment34 = ChatEntry(False, "{b}turb0g00se - 6:32{/b}\nNo trap! Where's my money??", 4, "#ffffff")
default vig4_sc2_4_comment35 = ChatEntry(False, "{b}bacon8r_6 - 6:32{/b}\nDamn, not with me rn, I'll get you on the next stream ;)", 4, "#ffffff")
default vig4_sc2_4_comment36 = ChatEntry(False, "{b}Coriolis - 6:33{/b}\nAwww, shield papa has a heart", 4, "#ffffff")
default vig4_sc2_4_comment37 = ChatEntry(False, "{b}R4dioRobbie - 6:33{/b}\nShield papa!", 4, "#ffffff")
default vig4_sc2_4_comment38 = ChatEntry(False, "{b}llamabama22 - 6:33{/b}\nI'll let him pop my shields any day", 4, "#ffffff")
default vig4_sc2_4_comment39 = ChatEntry(False, "{b}J4MIR0QU4I - 6:34{/b}\nSeriously tho, like, I think there are some things you should process with a professional", 4, "#ffffff")

###Comments vig4_sc2_5 - Start of Coil and Vega chat
default vig4_sc2_5_comment1 = ChatEntry(False, "{b}Coriolis - 6:35{/b}\nWe did it! Mission accomplished y'all!", 4, "#ffffff")
default vig4_sc2_5_comment2 = ChatEntry(False, "{b}pickledDragons - 6:35{/b}\nIdk, we still gotta see what 'shield papa' has to say for himself", 4, "#ffffff")
default vig4_sc2_5_comment3 = ChatEntry(False, "{b}kitcat - 6:35{/b}\nI'm just glad MAC's back in our sights. Didn't like him being gone after what happened with the Hounds", 4, "#ffffff")
default vig4_sc2_5_comment4 = ChatEntry(False, "{b}Coriolis - 6:36{/b}\nIt's not the worst greeting we've had in the last couple weeks haha", 4, "#ffffff")
default vig4_sc2_5_comment5 = ChatEntry(False, "{b}_lostinmetr0 - 6:36{/b}\nTrue", 4, "#ffffff")
default vig4_sc2_5_comment6 = ChatEntry(False, "{b}kitcat - 6:36{/b}\nWe've hit friends with worse greetings tbf", 4, "#ffffff")
default vig4_sc2_5_comment7 = ChatEntry(False, "{b}turb0g00se - 6:36{/b}\nI mean, you're not wrong...", 4, "#ffffff")
default vig4_sc2_5_comment8 = ChatEntry(False, "{b}pickledDragons - 6:36{/b}\nApologies don't let you off the hook", 4, "#ffffff")
default vig4_sc2_5_comment9 = ChatEntry(False, "{b}bacon8r_6 - 6:36{/b}\nfr", 4, "#ffffff")
default vig4_sc2_5_comment10 = ChatEntry(False, "{b}jerrybean784 - 6:37{/b}\nI feel some exposition coming on", 4, "#ffffff")

###Comments vig4_sc2_6 - Exposition with Coil and Vega
default vig4_sc2_6_comment1 = ChatEntry(True, "{b}AFKAngel - 6:38:{/b}\nWe buying this \"peaceful town\" business?", 4, "#ffffff", "vig4_sc2_peacefulTown")
default vig4_sc2_6_comment2 = ChatEntry(False, "{b}J4MIR0QU4I - 6:38{/b}\nFREEEEEDOM!", 4, "#ffffff")
default vig4_sc2_6_comment3 = ChatEntry(False, "{b}_lostinmetr0 - 6:38{/b}\nSounds kinda nice tbh", 4, "#ffffff")
default vig4_sc2_6_comment4 = ChatEntry(False, "{b}turb0g00se - 6:38{/b}\nYah if you ignore how boring it probably is lol", 4, "#ffffff")
default vig4_sc2_6_comment5 = ChatEntry(False, "{b}kitcat - 6:38{/b}\nWHAT!?", 4, "#ffffff")
default vig4_sc2_6_comment6 = ChatEntry(False, "{b}pickledDragons - 6:38{/b}\nOhhh ok now his character in Episode 3 makes a bit more sense", 4, "#ffffff")
default vig4_sc2_6_comment7 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:38{/b}\nI was wondering why Mr. Gatsby was so friendly", 4, "#ffffff")
default vig4_sc2_6_comment8 = ChatEntry(False, "{b}R4dioRobbie - 6:39{/b}\n\"Close.\" Riiiiight, we got you Coil ;)", 4, "#ffffff")
default vig4_sc2_6_comment9 = ChatEntry(True, "{b}AFKAngel - 6:39{/b}\nUgh, funding. The dream", 4, "#ffffff", "vig4_sc2_AFKDream")
default vig4_sc2_6_comment10 = ChatEntry(False, "{b}kitcat - 6:39{/b}\nThat makes Coil MAC's uncle!", 4, "#ffffff")
default vig4_sc2_6_comment11 = ChatEntry(False, "{b}Coriolis - 6:39{/b}\nAwww family reunion", 4, "#ffffff")
default vig4_sc2_6_comment12 = ChatEntry(False, "{b}bacon8r_6 - 6:39{/b}\nCan robots have uncles?", 4, "#ffffff")
default vig4_sc2_6_comment13 = ChatEntry(False, "{b}marxky8 - 6:39{/b}\nThis one does!", 4, "#ffffff")
default vig4_sc2_6_comment14 = ChatEntry(False, "{b}llamabama22 - 6:40{/b}\nAmen papa", 4, "#ffffff")
default vig4_sc2_6_comment15 = ChatEntry(False, "{b}Coriolis - 6:39{/b}\nThey're cute. I like them! (now that they're not aiming guns at us lol)", 4, "#ffffff")
default vig4_sc2_6_comment16 = ChatEntry(False, "{b}turb0g00se - 6:39{/b}\nIDk, I'm still holding off on judgment", 4, "#ffffff")
default vig4_sc2_6_comment17 = ChatEntry( False, "{b}_lostinmetr0 - 6:39{/b}\nSounds an awful lot like a certain Captain we know...", 4, "#ffffff")
default vig4_sc2_6_comment18 = ChatEntry( False, "{b}jerrybean784 - 6:40{/b}\nI wonder if young Coil had a lot of \"I have to do better\" moments as well haha", 4, "#ffffff")
default vig4_sc2_6_comment19 = ChatEntry( False, "{b}xxxP0tat0Pr0phetxxx - 6:40{/b}\nUh oh", 4, "#ffffff")
default vig4_sc2_6_comment20 = ChatEntry( False, "{b}marxky8 - 6:40{/b}\nOh come on now what was that look about???", 4, "#ffffff")
default vig4_sc2_6_comment21 = ChatEntry( False, "{b}pickledDragons - 6:40{/b}\nhere it comes", 4, "#ffffff")
default vig4_sc2_6_comment22 = ChatEntry(False, "{b}kitcat - 6:41{/b}\ndrop him", 4, "#ffffff")
default vig4_sc2_6_comment23 = ChatEntry(False, "{b}pickledDragons - 6:41{/b}\nI knew it", 4, "#ffffff")
default vig4_sc2_6_comment24 = ChatEntry(False, "{b}llamabama22 - 6:41{/b}\nShield Papa nooooo!", 4, "#ffffff")
default vig4_sc2_6_comment25 = ChatEntry(False, "{b}Coriolis - 6:41{/b}\noh shit are they really gonna make us say goodbye to MAC??", 4, "#ffffff")
default vig4_sc2_6_comment26 = ChatEntry(False, "{b}bacon8r_6 - 6:41{/b}\nOver our dead bodies", 4, "#ffffff")
default vig4_sc2_6_comment27 = ChatEntry(False, "{b}bacon8r_6 - 6:42{/b}\nhell yeah", 4, "#ffffff")
default vig4_sc2_6_comment28 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:42{/b}\nOver our dead bodies", 4, "#ffffff")
default vig4_sc2_6_comment29 = ChatEntry(False, "{b}Coriolis - 6:42{/b}\nThis was the plan since Oakley 1 tho", 4, "#ffffff")
default vig4_sc2_6_comment30 = ChatEntry(False, "{b}kitcat - 6:42{/b}\nPlans change when you have a baby!", 4, "#ffffff")
default vig4_sc2_6_comment31 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:42{/b}\nWoahwoahwoah we're just rolling over now?", 4, "#ffffff")
default vig4_sc2_6_comment32 = ChatEntry(False, "{b}Coriolis - 6:42{/b}\nNo, we're making the hard choice", 4, "#ffffff")
default vig4_sc2_6_comment33 = ChatEntry(False, "{b}kitcat - 6:42{/b}\nScrew the hard choice, I want my son!", 4, "#ffffff")
default vig4_sc2_6_comment34 = ChatEntry(False, "{b}_lostinmetr0 - 6:42{/b}\nHoly shit I'm so conflicted", 4, "#ffffff")
default vig4_sc2_6_comment35 = ChatEntry(False, "{b}_turb0g00se - 6:43{/b}\ny tho, they can't just take our kid", 4, "#ffffff")
default vig4_sc2_6_comment36 = ChatEntry(False, "{b}J4MIR0QU4I - 6:43{/b}\nIt's not BigCorp though, they haven't done anything wrong", 4, "#ffffff")
default vig4_sc2_6_comment37 = ChatEntry(False, "{b}pickledDragons - 6:43{/b}\nDoesn't mean they're right", 4, "#ffffff")
default vig4_sc2_6_comment38 = ChatEntry(False, "{b}J4MIR0QU4I - 6:43{/b}\nTrue, but sometimes letting go is the heroic thing?", 4, "#ffffff")
default vig4_sc2_6_comment39 = ChatEntry(False, "{b}bacon8r_6 - 6:44{/b}\nNot what I would've done", 4, "#ffffff")
default vig4_sc2_6_comment40 = ChatEntry(False, "{b}R4dioRobbie - 6:44{/b}\nIf you don't come back with good news Shield Papa, we're razing this place to the ground", 4, "#ffffff")
default vig4_sc2_6_comment41 = ChatEntry(False, "{b}llamabama22 - 6:44{/b}\nI mean, the man deserves a {i}bit{/i} of respect at least, no?", 4, "#ffffff")
default vig4_sc2_6_comment42 = ChatEntry(False, "{b}treb.ell - 6:45{/b}\nHey [player]! So glad I could make it!", 4, "#ffffff")
default vig4_sc2_6_comment43 = ChatEntry(True, "{b}treb.ell - 6:45{/b}\nWow there are a lot of peeps in chat. What'd I miss so far?", 4, "#ffffff", "vig4_sc2_elliotEntrance")

###Comments vig4_bro - For the interaction when your brother enters chat
default vig4_bro_comment1 = ChatEntry(False, "{b}treb.ell - 6:45{/b}\nI was! But we rescheduled to tomorrow! They rearranged some plans so I could be here for this :)", 4, "#ffffff")
default vig4_bro_comment2 = ChatEntry(False, "{b}treb.ell - 6:45{/b}\nIt's great to be here! Was able to reschedule plans so I could make it. Figured I'd surprise you :)", 4, "#ffffff")
default vig4_bro_comment3 = ChatEntry(False, "{b}Coriolis - 6:45{/b}\nWelcome to the stream!", 4, "#ffffff")
default vig4_bro_comment4 = ChatEntry(False, "{b}kitcat - 6:45{/b}\nHi lil' [streamer]!", 4, "#ffffff")
default vig4_bro_comment5 = ChatEntry(False, "{b}pickledDragons - 6:45{/b}\nGood to have you on board!", 4, "#ffffff")
default vig4_bro_comment6 = ChatEntry(False, "{b}turb0g00se - 6:45{/b}\@ treb.ell, your big sib is a legend!", 4, "#ffffff")
default vig4_bro_comment7 = ChatEntry(False, "{b}_lostinmer0 - 6:45{/b}\nHi!", 4, "#ffffff")
default vig4_bro_comment8 = ChatEntry(False, "{b}bacon8r_6 - 6:45{/b}\nHi!", 4, "#ffffff")
default vig4_bro_comment9 = ChatEntry(False, "{b}AFKAngel - 6:45{/b}\nHello!", 4, "#ffffff")
default vig4_bro_comment10 = ChatEntry(False, "{b}marxky8 - 6:45{/b}\Caw Caw! Hiss Hiss!", 4, "#ffffff")
default vig4_bro_comment11 = ChatEntry(False, "{b}treb.ell - 6:45{/b}\nOh wow, that's a lot of people. Hi everyone!", 4, "#ffffff")
default vig4_bro_comment12 = ChatEntry(False, "{b}treb.ell - 6:45{/b}\nCaw Caw Hiss Hiss!", 4, "#ffffff")
default vig4_bro_comment13 = ChatEntry(False, "{b}llamabama22 - 6:46{/b}\nOk we do have to catch him up though cause things are about to pop off", 4, "#ffffff")
default vig4_bro_comment14 = ChatEntry(False, "{b}treb.ell - 6:46{/b}\nI would hope so for a finale lol", 4, "#ffffff")
default vig4_bro_comment15 = ChatEntry(False, "{b}_lostinmetr0 - 6:46{/b}\nAnd he's got a cool daughter who lowkey looks like she could kick some ass", 4, "#ffffff")
default vig4_bro_comment16 = ChatEntry(False, "{b}R4dioRobbie - 6:46{/b}\nTell him why the suck tho!", 4, "#ffffff")
default vig4_bro_comment17 = ChatEntry(False, "{b}treb.ell - 6:46{/b}\nNo!", 4, "#ffffff")
default vig4_bro_comment18 = ChatEntry(False, "{b}pickledDragons - 6:46{/b}\nThey're doing this whole \"the organization doesn't want you\" thing", 4, "#ffffff")
default vig4_bro_comment19 = ChatEntry(False, "{b}Coriolis - 6:46{/b}\nBut Coil's gonna talk with the higher ups to try to swing it our way", 4, "#ffffff")
default vig4_bro_comment20 = ChatEntry(False, "{b}treb.ell - 6:46{/b}\nOk so, big dramatic \"maybe we have to say goodbye to MAC\" type situation but also, we get a beach episode?", 4, "#ffffff")
default vig4_bro_comment21 = ChatEntry(False, "{b}kitCat - 6:46{/b}\nHe gets it!", 4, "#ffffff")
default vig4_bro_comment22 = ChatEntry(False, "{b}AFKAngel - 6:47{/b}\nWait! Tea leaves! Who's your fave Oakley character @treb.ell??", 4, "#ffffff")
default vig4_bro_comment23 = ChatEntry(False, "{b}treb.ell - 6:47{/b}\nWell, I know he's not gonna show up in this episode, but it's Allistar!", 4, "#ffffff")
default vig4_bro_comment24 = ChatEntry(False, "{b}_lostinmer0 - 6:47{/b}\nOMG, [streamer] offed their sibling's favorite character?", 4, "#ffffff")
default vig4_bro_comment25 = ChatEntry(False, "{b}turb0g00se - 6:47{/b}\nLegend", 4, "#ffffff")
default vig4_bro_comment26 = ChatEntry(False, "{b}bacon8r_6 - 6:47{/b}\nWow we really are watching the true Outlaw", 4, "#ffffff")
default vig4_bro_comment27 = ChatEntry(False, "{b}treb.ell - 6:47{/b}\nSounds good, Cap!", 4, "#ffffff")

###Comments vig4_sc3_1 - Festival start
default vig4_sc3_1_comment1 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:48{/b}\nThat's the kid of the old guy we're not crazy about", 4, "#ffffff")
default vig4_sc3_1_comment2 = ChatEntry(False, "{b}llamabama22 - 6:48{/b}\nSpeak for yourself, I like Shield Papa Coil", 4, "#ffffff")
default vig4_sc3_1_comment3 = ChatEntry(False, "{b}AFKAngel - 6:48{/b}\nWell usually our celebrations involve betting our ship on a drinking game lol", 4, "#ffffff")
default vig4_sc3_1_comment4 = ChatEntry(False, "{b}_lostinmetr0 - 6:49{/b}\nOh do we get to pick our date??", 4, "#ffffff")
default vig4_sc3_1_comment5 = ChatEntry(False, "{b}treb.ell - 6:49{/b}\nI hope so!", 4, "#ffffff")
default vig4_sc3_1_comment6 = ChatEntry(False, "{b}Coriolis - 6:49{/b}\nOoh yes, pick Jennica!", 4, "#ffffff")
default vig4_sc3_1_comment7 = ChatEntry(False, "{b}kitcat - 6:49{/b}\nMoresa is the path!", 4, "#ffffff")
default vig4_sc3_1_comment8 = ChatEntry(False, "{b}pickledDragons - 6:49{/b}\nNo, you gotta hold off for the secret romance!", 4, "#ffffff")
default vig4_sc3_1_comment9 = ChatEntry(False, "{b}kitcat - 6:49{/b}\nNo we have to hold off for the Ama romance, remember!", 4, "#ffffff")
default vig4_sc3_1_comment10 = ChatEntry(False, "{b}treb.ell - 6:50{/b}\nWait! I wanna see what Vega's deal is!", 4, "#ffffff")
default vig4_sc3_1_comment11 = ChatEntry(False, "{b}treb.ell - 6:51{/b}\nOoh also, this track slaps", 4, "#ffffff")

###Comments vig4_sc3_2_vega - "Date" scene with Vega
default vig4_sc3_2_vega_comment1 = ChatEntry(False, "{b}treb.ell - 6:50{/b}\nYes, thank you!", 4, "#ffffff")
default vig4_sc3_2_vega_comment2 = ChatEntry(True, "{b}kitcat - 6:50{/b}\nBoooo where's the romance?", 4, "#ffffff", "vig4_sc3_festivalRomance")
default vig4_sc3_2_vega_comment3 = ChatEntry(False, "{b}Coriolis - 6:50{/b}\nDamn, hope there's a secret romance option then", 4, "#ffffff")
default vig4_sc3_2_vega_comment4 = ChatEntry(False, "{b}PickledDragons - 6:50{/b}\I like this, wanna see what makes this person tick", 4, "#ffffff")
default vig4_sc3_2_vega_comment5 = ChatEntry(False, "{b}R4dioRobbie - 6:51{/b}\nThis kid doesn't know what she's getting into", 4, "#ffffff")
default vig4_sc3_2_vega_comment6 = ChatEntry(False, "{b}llamabama22 - 6:52{/b}\nShe did seem pretty handy with a rifle earlier...", 4, "#ffffff")
default vig4_sc3_2_vega_comment7 = ChatEntry(False, "{b}treb.ell - 6:52{/b}\nOk ok, she can hold her own!", 4, "#ffffff")
default vig4_sc3_2_vega_comment8 = ChatEntry(False, "{b}_lostinmetr0 - 6:52{/b}\nIs it bad I kinda want Vega to win??", 4, "#ffffff")
default vig4_sc3_2_vega_comment9 = ChatEntry(False, "{b}jerrybean784 - 6:52{/b}\nC'mon Moze!", 4, "#ffffff")
default vig4_sc3_2_vega_comment10 = ChatEntry(False, "{b}J4MIR0QU4I - 6:53{/b}\nIt doesn't mean anything, let the kid have the win!", 4, "#ffffff")
default vig4_sc3_2_vega_comment11 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:53{/b}\nVega wouldn't want to win if she knew you let up. Finish strong!", 4, "#ffffff")
default vig4_sc3_2_vega_comment12 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:53{/b}\nDamn", 4, "#ffffff")
default vig4_sc3_2_vega_comment13 = ChatEntry(False, "{b}J4MIR0QU4I - 6:53{/b}\nCompetition breeds competition", 4, "#ffffff")
default vig4_sc3_2_vega_comment14 = ChatEntry(False, "{b}bacon8r_6 - 6:53{/b}\nShe for sure knew what she was doing", 4, "#ffffff")
default vig4_sc3_2_vega_comment15 = ChatEntry(False, "{b}AFKAngel - 6:53{/b}\nTalented engineer and good with a rifle. Would make a good outlaw", 4, "#ffffff")
default vig4_sc3_2_vega_comment16 = ChatEntry(False, "{b}Coriolis - 6:54{/b}\nI mean, she's basically already a freedom fighter", 4, "#ffffff")
default vig4_sc3_2_vega_comment17 = ChatEntry(False, "{b}_lostinmetr0 - 6:54{/b}\nI'd fight for freedom with her!", 4, "#ffffff")
default vig4_sc3_2_vega_comment18 = ChatEntry(False, "{b}treb.ell - 6:55{/b}\nSo funny to me how these kinds of questions make sense even for Marshal Moze haha", 4, "#ffffff")
default vig4_sc3_2_vega_comment19 = ChatEntry(False, "{b}AFKAngel - 6:55{/b}\n\"you're so direct\" is basically her catch phrase", 4, "#ffffff")
default vig4_sc3_2_vega_comment20 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:55{/b}\nThat and, \"I didn't have a choice\" hahaha", 4, "#ffffff")
default vig4_sc3_2_vega_comment21 = ChatEntry(False, "{b}kitcat - 6:55{/b}\nnot the \"I had to murder as a child\" trauma :(", 4, "#ffffff")
default vig4_sc3_2_vega_comment22 = ChatEntry(False, "{b}R4dioRobbie - 6:56{/b}\nI feel like people don't talk about how dark this universe can be at times", 4, "#ffffff")
default vig4_sc3_2_vega_comment23 = ChatEntry(False, "{b}treb.ell - 6:56{/b}\nOh yeah, especially if you check out the official web comics. The stuff in the lore is {i}crazy{/i}", 4, "#ffffff")
default vig4_sc3_2_vega_comment24 = ChatEntry(False, "{b}treb.ell - 6:56{/b}\nIt's why Outlaw Moze makes any kind of sense as a character", 4, "#ffffff")
default vig4_sc3_2_vega_comment25 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\nNice to know that Moze's notoriety can be inspiring", 4, "#ffffff")
default vig4_sc3_2_vega_comment26 = ChatEntry(False, "{b}kitcat - 6:57{/b}\nYes! More badass women on the crew!", 4, "#ffffff")
default vig4_sc3_2_vega_comment27 = ChatEntry(False, "{b}kitcat - 6:57{/b}\ndamn", 4, "#ffffff")
default vig4_sc3_2_vega_comment28 = ChatEntry(False, "{b}_lostinmetr0 - 6:57{/b}\nworth a shot", 4, "#ffffff")

###Comments vig4_sc3_2_jennica - Date scene with Jennica
default vig4_sc3_2_jenn_comment1 = ChatEntry(False, "{b}Coriolis - 6:50{/b}\nYes! Jenn best girl!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment2 = ChatEntry(False, "{b}marxky8 - 6:50{/b}\nButter my biscuits!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment3 = ChatEntry(False, "{b}kitcat - 6:50{/b}\nDon't mind me, I'll just cope in my corner real quick", 4, "#ffffff")
default vig4_sc3_2_jenn_comment4 = ChatEntry(False, "{b}AFKAngel - 6:51{/b}\nNo way, Jenn's a gamer!?", 4, "#ffffff")
default vig4_sc3_2_jenn_comment5 = ChatEntry(False, "{b}bacon8r_6 - 6:51{/b}\nOne of us. One of us.", 4, "#ffffff")
default vig4_sc3_2_jenn_comment6 = ChatEntry(False, "{b}turb0g00se - 6:51{/b}\nSame, I learned to drive by playing Mario Kart", 4, "#ffffff")
default vig4_sc3_2_jenn_comment7 = ChatEntry(False, "{b}jerrybean784 - 6:51{/b}\nRemind me never to get in a car with you then lol", 4, "#ffffff")
default vig4_sc3_2_jenn_comment8 = ChatEntry(False, "{b}pickledDragons - 6:52{/b}\nMoze is about to get worked!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment9 = ChatEntry(False, "{b}marxky8 - 6:52{/b}\nA bit rude", 4, "#ffffff")
default vig4_sc3_2_jenn_comment10 = ChatEntry(False, "{b}Coriolis - 6:52{/b}\nAll's fair in love and war", 4, "#ffffff")
default vig4_sc3_2_jenn_comment11 = ChatEntry(False, "{b}kitcat - 6:52{/b}\n^^especially love", 4, "#ffffff")
default vig4_sc3_2_jenn_comment12 = ChatEntry(True, "{b}treb.ell - 6:53{/b}\nThis banter reminds me of playing Smash Bros. when we were younger :)", 4, "#ffffff", "vig4_sc3_elMemory")
default vig4_sc3_2_jenn_comment13 = ChatEntry(False, "{b}turb0g00se - 6:53{/b}\nGo get her!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment14 = ChatEntry(False, "{b}pickledDragons - 6:53{/b}\nDon't overcommit!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment15 = ChatEntry(False, "{b}J4MIR0QU4I - 6:54{/b}\nClever girl", 4, "#ffffff")
default vig4_sc3_2_jenn_comment16 = ChatEntry(False, "{b}_lostinmetr0 - 6:54{/b}\nPlayed us llike a fiddle", 4, "#ffffff")
default vig4_sc3_2_jenn_comment17 = ChatEntry(False, "{b}Coriolis - 6:54{/b}\nWell, she is a professional", 4, "#ffffff")
default vig4_sc3_2_jenn_comment18 = ChatEntry(False, "{b}llamabama22 - 6:55{/b}\nRespectful, glad there's no salt", 4, "#ffffff")
default vig4_sc3_2_jenn_comment19 = ChatEntry(False, "{b}R4dioRobbie - 6:55{/b}\nI'd be so salty lol", 4, "#ffffff")
default vig4_sc3_2_jenn_comment20 = ChatEntry(False, "{b}J4MIR0QU4I - 6:54{/b}\nWait, can you actually beat her??", 4, "#ffffff")
default vig4_sc3_2_jenn_comment21 = ChatEntry(False, "{b}_lostinmetr0 - 6:54{/b}\ncheckmate!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment22 = ChatEntry(False, "{b}Coriolis - 6:54{/b}\nWow, Moze must've been some pilot!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment23 = ChatEntry(False, "{b}bacon8r_6 - 6:54{/b}\nBlaze of glory!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment24 = ChatEntry(False, "{b}J4MIR0QU4I - 6:54{/b}\nHonestly, kind of feels like a win", 4, "#ffffff")
default vig4_sc3_2_jenn_comment25 = ChatEntry(False, "{b}_lostinmetr0 - 6:54{/b}\nFor real", 4, "#ffffff")
default vig4_sc3_2_jenn_comment26 = ChatEntry(False, "{b}Coriolis - 6:54{/b}\nBad position, but Moze found a way to even the playing field!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment27 = ChatEntry(False, "{b}bacon8r_6 - 6:54{/b}\nI don't know about this...", 4, "#ffffff")
default vig4_sc3_2_jenn_comment28 = ChatEntry(False, "{b}J4MIR0QU4I - 6:54{/b}\nlmao wut???", 4, "#ffffff")
default vig4_sc3_2_jenn_comment29 = ChatEntry(False, "{b}_lostinmetr0 - 6:54{/b}\nThat's...yeah that's one way to do it I guess", 4, "#ffffff")
default vig4_sc3_2_jenn_comment30 = ChatEntry(False, "{b}Coriolis - 6:54{/b}\nHoly shit she's a badass", 4, "#ffffff")
default vig4_sc3_2_jenn_comment31 = ChatEntry(False, "{b}marxky8 - 6:55{/b}\nRed flag", 4, "#ffffff")
default vig4_sc3_2_jenn_comment32 = ChatEntry(False, "{b}bacon8r_6 - 6:55{/b}\nWorst career day ever", 4, "#ffffff")
default vig4_sc3_2_jenn_comment33 = ChatEntry(False, "{b}kitcat - 6:55{/b}\nAww, Jenn, you're so much better than that dude!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment34 = ChatEntry(False, "{b}Coriolis - 6:55{/b}\nope is this the moment??", 4, "#ffffff")
default vig4_sc3_2_jenn_comment35 = ChatEntry(False, "{b}Coriolis - 6:56{/b}\nWhaaaaaat?", 4, "#ffffff")
default vig4_sc3_2_jenn_comment36 = ChatEntry(False, "{b}kitcat - 6:56{/b}\nListen, I was Team Teresa all day, but are we really skipping any kind of romance?", 4, "#ffffff")
default vig4_sc3_2_jenn_comment37 = ChatEntry(False, "{b}pickledDragons - 6:56{/b}\nEyes on the prize, Ama's still out there", 4, "#ffffff")
default vig4_sc3_2_jenn_comment38 = ChatEntry(False, "{b}_lostinmetr0 - 6:56{/b}\n{i}If{/i} they coded that in", 4, "#ffffff")
default vig4_sc3_2_jenn_comment39 = ChatEntry(False, "{b}_lostinmetr0 - 6:56{/b}\nOh come on, just say it already Moze!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment40 = ChatEntry(False, "{b}AFKAngel - 6:56{/b}\nTell her it's a backside worth watching!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment41 = ChatEntry(False, "{b}Coriolis - 6:56{/b}\nYes! And then??", 4, "#ffffff")
default vig4_sc3_2_jenn_comment42 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\nYeeeesssss!!!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment43 = ChatEntry(False, "{b}treb.ell - 6:57{/b}\nWay to go Moze!", 4, "#ffffff")
default vig4_sc3_2_jenn_comment44 = ChatEntry(False, "{b}llamabama22 - 6:57{/b}\nLove at first...well, thousandth sight?", 4, "#ffffff")
default vig4_sc3_2_jenn_comment45 = ChatEntry(False, "{b}_lostinmetr0 - 6:57{/b}\nbest friends = best couple", 4, "#ffffff")
default vig4_sc3_2_jenn_comment46 = ChatEntry(False, "{b}kitcat - 6:57{/b}\nOk, I was team Teresa, but that was really cute :)", 4, "#ffffff")
default vig4_sc3_2_jenn_comment47 = ChatEntry(False, "{b}J4MIR0QU4I - 6:57{/b}\nHoly shit", 4, "#ffffff")
default vig4_sc3_2_jenn_comment48 = ChatEntry(False, "{b}_lostinmetr0 - 6:57{/b}\nno way", 4, "#ffffff")
default vig4_sc3_2_jenn_comment49 = ChatEntry(False, "{b}kitcat - 6:57{/b}\nis this really happening", 4, "#ffffff")
default vig4_sc3_2_jenn_comment50 = ChatEntry(False, "{b}marxky8 - 6:57{/b}\nomfg", 4, "#ffffff")
default vig4_sc3_2_jenn_comment51 = ChatEntry(False, "{b}llamabama22 - 6:57{/b}\nThat's {i}BRUTAL{/i}", 4, "#ffffff")
default vig4_sc3_2_jenn_comment52 = ChatEntry(False, "{b}treb.ell - 6:57{/b}\nIf this happened to me I think I would legitimately die on the spot", 4, "#ffffff")
default vig4_sc3_2_jenn_comment53 = ChatEntry(False, "{b}J4MIR0QU4I - 6:57{/b}\n@Coriolis, you doing okay", 4, "#ffffff")
default vig4_sc3_2_jenn_comment54 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\n...", 4, "#ffffff")
default vig4_sc3_2_jenn_comment55 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\nI'm gonna need some time guys", 4, "#ffffff")
default vig4_sc3_2_jenn_comment56 = ChatEntry(False, "{b}kitcat - 6:57{/b}\n@Coriolis: <3", 4, "#ffffff")
default vig4_sc3_2_jenn_comment57 = ChatEntry(False, "{b}pickledDragons - 6:57{/b}\n@Coriolis: <3", 4, "#ffffff")

###Comments vig4_sc3_2_teresa - Date scene with Teresa
default vig4_sc3_2_resa_comment1 = ChatEntry(False, "{b}kitcat - 6:50{/b}\nBadass engineer!", 4, "#ffffff")
default vig4_sc3_2_resa_comment2 = ChatEntry(False, "{b}turb0g00se - 6:50{/b}\nI see we're moving toward the \"Conflagration Phase\"", 4, "#ffffff")
default vig4_sc3_2_resa_comment3 = ChatEntry(False, "{b}Coriolis - 6:50{/b}\nBut Jenn's been there since day one!", 4, "#ffffff")
default vig4_sc3_2_resa_comment4 = ChatEntry(False, "{b}bacon8r_6 - 6:51{/b}\nOoh yea, time to earn some money", 4, "#ffffff")
default vig4_sc3_2_resa_comment5 = ChatEntry(False, "{b}kitcat - 6:51{/b}\nOh this was in that one movie!", 4, "#ffffff")
default vig4_sc3_2_resa_comment6 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:51{/b}\nTime to bet the ship?", 4, "#ffffff")
default vig4_sc3_2_resa_comment7 = ChatEntry(False, "{b}jerrybean784 - 6:51{/b}\nThey didn't actually do that tho", 4, "#ffffff")
default vig4_sc3_2_resa_comment8 = ChatEntry(False, "{b}pickledDragons - 6:51{/b}\nWow, Teresa really did some psychic damage to these guys", 4, "#ffffff")
default vig4_sc3_2_resa_comment9 = ChatEntry(False, "{b}R4dioRobbie - 6:52{/b}\nTeresa used \"Intimidate\"", 4, "#ffffff")
default vig4_sc3_2_resa_comment10 = ChatEntry(False, "{b}turb0g00se - 6:52{/b}\nIt's super effective!", 4, "#ffffff")
default vig4_sc3_2_resa_comment11 = ChatEntry(False, "{b}_lostinmetr0 - 6:52{/b}\ndon't call, it's too early!", 4, "#ffffff")
default vig4_sc3_2_resa_comment12 = ChatEntry(False, "{b}llamabama22 - 6:52{/b}\nEven I knew that wasn't a great call", 4, "#ffffff")
default vig4_sc3_2_resa_comment13 = ChatEntry(False, "{b}AFKAngel - 6:52{/b}\nTrying to lower her guard?", 4, "#ffffff")
default vig4_sc3_2_resa_comment14 = ChatEntry(False, "{b}treb.ell - 6:52{/b}\nLet it ride!", 4, "#ffffff")
default vig4_sc3_2_resa_comment15 = ChatEntry(False, "{b}kitcat - 6:52{/b}\nlove her confidence", 4, "#ffffff")
default vig4_sc3_2_resa_comment16 = ChatEntry(False, "{b}bacon8r_6 - 6:52{/b}\nOne of these mooks is gonna crack", 4, "#ffffff")
default vig4_sc3_2_resa_comment17 = ChatEntry(False, "{b}turb0g00se - 6:52{/b}\ntoo ez", 4, "#ffffff")
default vig4_sc3_2_resa_comment18 = ChatEntry(False, "{b}xXpearlXx - 6:53{/b}\nAre we up?", 4, "#ffffff")
default vig4_sc3_2_resa_comment19 = ChatEntry(False, "{b}marxky8 - 6:53{/b}\nNah, Teresa's barely lost", 4, "#ffffff")
default vig4_sc3_2_resa_comment20 = ChatEntry(False, "{b}treb.ell - 6:53{/b}\nTime to get her [streamer]!", 4, "#ffffff")
default vig4_sc3_2_resa_comment21 = ChatEntry(False, "{b}turb0g00se - 6:53{/b}\nScrew it, we don't have any. call her!", 4, "#ffffff")
default vig4_sc3_2_resa_comment22 = ChatEntry(False, "{b}pickledDragons - 6:53{/b}\nBe patient, let her make the mistake!", 4, "#ffffff")
default vig4_sc3_2_resa_comment23 = ChatEntry(False, "{b}jerrybean784 - 6:53{/b}\nWow that was closer than I expected", 4, "#ffffff")
default vig4_sc3_2_resa_comment24 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:53{/b}\nTeresa stays winning", 4, "#ffffff")
default vig4_sc3_2_resa_comment25 = ChatEntry(False, "{b}AFKAngel - 6:53{/b}\nuh oh, did we break her?", 4, "#ffffff")
default vig4_sc3_2_resa_comment26 = ChatEntry(False, "{b}R4dioRobbie - 6:53{/b}\nSore loser?", 4, "#ffffff")
default vig4_sc3_2_resa_comment27 = ChatEntry(False, "{b}R4dioRobbie - 6:53{/b}\nsore winner?", 4, "#ffffff")
default vig4_sc3_2_resa_comment28 = ChatEntry(False, "{b}kitcat - 6:53{/b}\nNo there's something else going on here", 4, "#ffffff")
default vig4_sc3_2_resa_comment29 = ChatEntry(False, "{b}bacon8r_6 - 6:53{/b}\ncan't stop won't stop", 4, "#ffffff")
default vig4_sc3_2_resa_comment30 = ChatEntry(False, "{b}jerrybean784 - 6:53{/b}\nWe got her!", 4, "#ffffff")
default vig4_sc3_2_resa_comment31 = ChatEntry(False, "{b}bacon8r_6 - 6:53{/b}\nTeresa can't run the table on us!", 4, "#ffffff")
default vig4_sc3_2_resa_comment32 = ChatEntry(False, "{b}bacon8r_6 - 6:53{/b}\ncan't stop won't stop", 4, "#ffffff")
default vig4_sc3_2_resa_comment33 = ChatEntry(False, "{b}_lostinmetr0 - 6:53{/b}\nI think that's too far", 4, "#ffffff")
default vig4_sc3_2_resa_comment34 = ChatEntry(False, "{b}pickledDragons - 6:53{/b}\nYeah, pushed your luck too hard", 4, "#ffffff")
default vig4_sc3_2_resa_comment35 = ChatEntry(False, "{b}kitcat - 6:54{/b}\nYea see there's the insecurity", 4, "#ffffff")
default vig4_sc3_2_resa_comment36 = ChatEntry(False, "{b}marxky8 - 6:54{/b}\Crazy that she still feels like she's on the outside of the group", 4, "#ffffff")
default vig4_sc3_2_resa_comment37 = ChatEntry(False, "{b}treb.ell - 6:54{/b}\nThere's a really cool comic that gets into her back story and how she shamed her farmily", 4, "#ffffff")
default vig4_sc3_2_resa_comment38 = ChatEntry(False, "{b}kitcat - 6:54{/b}\nThis is it!", 4, "#ffffff")
default vig4_sc3_2_resa_comment39 = ChatEntry(False, "{b}kitcat - 6:55{/b}\nWoah woah what? Why?", 4, "#ffffff")
default vig4_sc3_2_resa_comment40 = ChatEntry(False, "{b}Coriolis - 6:55{/b}\nI mean, I was fully on the Jennica bandwagon, but are we just skipping any romance altogether?", 4, "#ffffff")
default vig4_sc3_2_resa_comment41 = ChatEntry(False, "{b}pickledDragons - 6:55{/b}\nEyes on the prize, Ama's still out there", 4, "#ffffff")
default vig4_sc3_2_resa_comment42 = ChatEntry(False, "{b}_lostinmetr0 - 6:56{/b}\n{i}If{/i} they coded that in", 4, "#ffffff")
default vig4_sc3_2_resa_comment43 = ChatEntry(False, "{b}kitcat - 6:54{/b}\nKISS HER ALREADY", 4, "#ffffff")
default vig4_sc3_2_resa_comment44 = ChatEntry(False, "{b}xXpearlXx - 6:56{/b}\nit had to happen cause you're fine", 4, "#ffffff")
default vig4_sc3_2_resa_comment45 = ChatEntry(False, "{b}kitcat - 6:56{/b}\nomg", 4, "#ffffff")
default vig4_sc3_2_resa_comment46 = ChatEntry(False, "{b}kitcat - 6:56{/b}\nYESSSS!!!", 4, "#ffffff")
default vig4_sc3_2_resa_comment47 = ChatEntry(False, "{b}treb.ell - 6:57{/b}\nWay to go Moze!", 4, "#ffffff")
default vig4_sc3_2_resa_comment48 = ChatEntry(False, "{b}llamabama22 - 6:57{/b}\nLove at first statistical improbability", 4, "#ffffff")
default vig4_sc3_2_resa_comment49 = ChatEntry(False, "{b}marxky8 - 6:57{/b}\nThey balance each other's crazy", 4, "#ffffff")
default vig4_sc3_2_resa_comment50 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\nOk, I was all for romancing Jennica, but that was really sweet!", 4, "#ffffff")
default vig4_sc3_2_resa_comment51 = ChatEntry(False, "{b}J4MIR0QU4I - 6:57{/b}\nHoly shit", 4, "#ffffff")
default vig4_sc3_2_resa_comment52 = ChatEntry(False, "{b}marxky8 - 6:57{/b}\nno way", 4, "#ffffff")
default vig4_sc3_2_resa_comment53 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\nis this really happening", 4, "#ffffff")
default vig4_sc3_2_resa_comment54 = ChatEntry(False, "{b}_lostinmetr0 - 6:57{/b}\nomg", 4, "#ffffff")
default vig4_sc3_2_resa_comment55 = ChatEntry(False, "{b}llamabama22 - 6:57{/b}\nThat's {i}BRUTAL{/i}", 4, "#ffffff")
default vig4_sc3_2_resa_comment56 = ChatEntry(False, "{b}treb.ell - 6:57{/b}\nIf this happened to me I think I would legitimately die on the spot", 4, "#ffffff")
default vig4_sc3_2_resa_comment57 = ChatEntry(False, "{b}J4MIR0QU4I - 6:57{/b}\n@kitcat, you doing okay", 4, "#ffffff")
default vig4_sc3_2_resa_comment58 = ChatEntry(False, "{b}kitcat - 6:57{/b}\n...", 4, "#ffffff")
default vig4_sc3_2_resa_comment59 = ChatEntry(False, "{b}kitcat - 6:57{/b}\nNO", 4, "#ffffff")
default vig4_sc3_2_resa_comment60 = ChatEntry(False, "{b}Coriolis - 6:57{/b}\n@kitcat: <3", 4, "#ffffff")
default vig4_sc3_2_resa_comment61 = ChatEntry(False, "{b}pickledDragons - 6:57{/b}\n@kitcat: <3", 4, "#ffffff")

###Comments vig4_sc3_3 - One-on-One with Coil
default vig4_sc3_3_comment1 = ChatEntry(False, "{b}xXpearlXx - 6:58{/b}\nThat's so cute, it's MAC's own story time!", 4, "#ffffff")
default vig4_sc3_3_comment2 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:58{/b}\nDo you think he mentioned the part where we attacked an aid station?", 4, "#ffffff")
default vig4_sc3_3_comment3 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:58{/b}\nDo you think he mentioned the part where infiltrated an aid station?", 4, "#ffffff")
default vig4_sc3_3_comment4 = ChatEntry(False, "{b}bacon8r_6 - 6:58{/b}\nNooo MAC's not a snitch", 4, "#ffffff")
default vig4_sc3_3_comment5 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 6:58{/b}\nDo you think he told them about holding Deadeye at gun point?", 4, "#ffffff")
default vig4_sc3_3_comment6 = ChatEntry(False, "{b}treb.ell - 6:59{/b}\nSo this is the scientist guy? MAC's \"uncle?\"", 4, "#ffffff")
default vig4_sc3_3_comment7 = ChatEntry(False, "{b}R4dioRobbie - 6:59{/b}\nYep, that's Shield Papa Coil", 4, "#ffffff")
default vig4_sc3_3_comment8 = ChatEntry(False, "{b}kitcat - 6:59{/b}\nlil guy's learning the Marshal way <3", 4, "#ffffff")
default vig4_sc3_3_comment9 = ChatEntry(False, "{b}kitcat - 6:59{/b}\nlil guy's learning the Outlaw way <3", 4, "#ffffff")
default vig4_sc3_3_comment10 = ChatEntry(False, "{b}_lostinmetr0 - 7:00{/b}\nTwo proud parents talking about their kids", 4, "#ffffff")
default vig4_sc3_3_comment11 = ChatEntry(False, "{b}treb.ell - 7:00{/b}\nwoah, judgy grandpa", 4, "#ffffff")
default vig4_sc3_3_comment12 = ChatEntry(False, "{b}pickledDragons - 7:00{/b}\nOh yeah, he can be a bit of an ass", 4, "#ffffff")
default vig4_sc3_3_comment13 = ChatEntry(False, "{b}Coriolis - 7:00{/b}\nAfter everything we've done, can you blame him?", 4, "#ffffff")
default vig4_sc3_3_comment14 = ChatEntry(False, "{b}turb0g00se - 7:01{/b}\nWe're outlaws, but we're not evil..right?", 4, "#ffffff")
default vig4_sc3_3_comment15 = ChatEntry(False, "{b}bacon8r_6 - 7:01{/b}\nNah, I'm not in on that kind of self-doubt", 4, "#ffffff")
default vig4_sc3_3_comment16 = ChatEntry(False, "{b}J4MIR0QU4I - 7:01{/b}\nYou gotta evaluate yourself critically if you want to grow", 4, "#ffffff")
default vig4_sc3_3_comment17 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:01{/b}\nHell yeah, tell him Moze!", 4, "#ffffff")
default vig4_sc3_3_comment18 = ChatEntry(False, "{b}_lostinmetr0 - 7:01{/b}\nidk he makes a good point...", 4, "#ffffff")
default vig4_sc3_3_comment19 = ChatEntry(False, "{b}treb.ell - 7:01{/b}\nTbf, the game has been a little...dark so far. So I see where he's coming from", 4, "#ffffff")
default vig4_sc3_3_comment20 = ChatEntry(False, "{b}turb0g00se - 7:01{/b}\nI think we taught the kid well imo", 4, "#ffffff")
default vig4_sc3_3_comment21 = ChatEntry(False, "{b}kitcat - 7:01{/b}\nwoah woah woah, MAC is baby, of course that's our responsibilty", 4, "#ffffff")
default vig4_sc3_3_comment22 = ChatEntry(False, "{b}llamabama22 - 7:02{/b}\nShield Papa clutch!?", 4, "#ffffff")
default vig4_sc3_3_comment23 = ChatEntry(False, "{b}llamabama22 - 7:02{/b}\noh nvm", 4, "#ffffff")
default vig4_sc3_3_comment24 = ChatEntry(False, "{b}xXpearlXx - 7:02{/b}\nnooooo", 4, "#ffffff")
default vig4_sc3_3_comment25 = ChatEntry(False, "{b}pickledDragons - 7:02{/b}\nsaw that coming", 4, "#ffffff")
default vig4_sc3_3_comment26 = ChatEntry(False, "{b}Coriolis - 7:02{/b}\nHeroes have to sacrifice, right?", 4, "#ffffff")
default vig4_sc3_3_comment27 = ChatEntry(False, "{b}kitcat - 7:02{/b}\nYeah, but this is too much", 4, "#ffffff")
default vig4_sc3_3_comment28 = ChatEntry(False, "{b}AFKAngel - 7:02{/b}\nAfter all we've done? We didn't even go that far Outlaw", 4, "#ffffff")
default vig4_sc3_3_comment29 = ChatEntry(False, "{b}R4dioRobbie - 7:02{/b}\nHow dare you, sir", 4, "#ffffff")
default vig4_sc3_3_comment30 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:02{/b}\nThis old guy doesn't know what it's like outside his little perfect commune", 4, "#ffffff")
default vig4_sc3_3_comment31 = ChatEntry(False, "{b}marxky8 - 7:02{/b}\nI bet he is", 4, "#ffffff")
default vig4_sc3_3_comment33 = ChatEntry(False, "{b}trub0g00se - 7:03{/b}\nConflagration time!", 4, "#ffffff")
default vig4_sc3_3_comment34 = ChatEntry(False, "{b}treb.ell - 7:03{/b}\nEven if it's true, that's a low blow", 4, "#ffffff")
default vig4_sc3_3_comment35 = ChatEntry(False, "{b}bacon8r_6 - 7:03{/b}\nGet his ass, Captain", 4, "#ffffff")
default vig4_sc3_3_comment36 = ChatEntry(True, "{b}pickledDragons - 7:03{/b}\nEven if he's trying to do the right thing, this is the wrong way to do it", 4, "#ffffff", "vig4_sc3_pdCoilCommentary")
default vig4_sc3_3_comment37 = ChatEntry(False, "{b}kitcat - 7:03{/b}\nNot the flashback montage!", 4, "#ffffff")
default vig4_sc3_3_comment38 = ChatEntry(False, "{b}xXpearlXx - 7:03{/b}\nNooo we have to fight this!", 4, "#ffffff")
default vig4_sc3_3_comment39 = ChatEntry(True, "{b}Coriolis - 7:03{/b}\nCoil's an ass, but he's not a bad guy. We can't be selfish at a time like this", 4, "#ffffff", "vig4_sc3_csCoilCommentary")
default vig4_sc3_3_comment40 = ChatEntry(False, "{b}xXpearlXx - 7:03{/b}\nRaze it to the ground!", 4, "#ffffff")
default vig4_sc3_3_comment41 = ChatEntry(False, "{b}jerrybean784 - 7:04{/b}\nOh, that's pretty dastardly", 4, "#ffffff")

###Comments vig4_sc3_4 - Start of conversation with MAC
default vig4_sc3_4_comment1 = ChatEntry(False, "{b}treb.ell - 7:04{/b}\nHe's so pure!", 4, "#ffffff")
default vig4_sc3_4_comment2 = ChatEntry(False, "{b}llamabama22 - 7:04{/b}\nWell this is gonna suck", 4, "#ffffff")
default vig4_sc3_4_comment3 = ChatEntry(False, "{b}kitcat - 7:04{/b}\nMAC they want to steal {i}you!{/i}", 4, "#ffffff")
default vig4_sc3_4_comment4 = ChatEntry(False, "{b}_lostinmetr0 - 7:04{/b}\nWe brought him here for this", 4, "#ffffff")
default vig4_sc3_4_comment5 = ChatEntry(False, "{b}bacon8r_6 - 7:04{/b}\nThings change. It's just not fair", 4, "#ffffff")
default vig4_sc3_4_comment6 = ChatEntry(False, "{b}J4MIR0QU4I - 7:04{/b}\nAre we doing better or are we going for violence? It's been the question the whole game, it's gotta happen one more time", 4, "#ffffff")
default vig4_sc3_4_comment7 = ChatEntry(False, "{b}turb0g00se - 7:05{/b}\nHe's becoming a person! And I don't trust Coil to teach him \"how to live\"", 4, "#ffffff")
default vig4_sc3_4_comment8 = ChatEntry(False, "{b}Coriolis - 7:05{/b}\nIt's the only way. What's the point if we're not making the world a better place?", 4, "#ffffff")
default vig4_sc3_4_comment9 = ChatEntry(False, "{b}R4dioRobbie - 7:05{/b}\nI don't even know lol", 4, "#ffffff")
default vig4_sc3_4_comment10 = ChatEntry(False, "{b}R4dioRobbie - 7:05{/b}\nSo are we lying to the kid or does Moze really believe that?", 4, "#ffffff")
default vig4_sc3_4_comment11 = ChatEntry(False, "{b}R4dioRobbie - 7:05{/b}\nWe've helped where we can. that's what matters", 4, "#ffffff")
default vig4_sc3_4_comment12 = ChatEntry(False, "{b}R4dioRobbie - 7:05{/b}\nBrutal, but honest", 4, "#ffffff")
default vig4_sc3_4_comment13 = ChatEntry(False, "{b}R4dioRobbie - 7:05{/b}\nAre we lying so goodbye will be easier?", 4, "#ffffff")
default vig4_sc3_4_comment14 = ChatEntry(False, "{b}pickledDragons - 7:05{/b}\nIt's the only way", 4, "#ffffff")
default vig4_sc3_4_comment15 = ChatEntry(False, "{b}bacon8r_6 - 7:05{/b}\nlike bacon", 4, "#ffffff")
default vig4_sc3_4_comment16 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:05{/b}\nsounding a little \"dark side-y\" there, Moze", 4, "#ffffff")
default vig4_sc3_4_comment17 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:05{/b}\ntough lesson, but necessary for the kid", 4, "#ffffff")

###Comments vig4_sc3_5 - Goodbye to MAC
default vig4_sc3_5_comment1 = ChatEntry(False, "{b}turb0g00se - 7:06{/b}\nWell that's vague", 4, "#ffffff")
default vig4_sc3_5_comment2 = ChatEntry(False, "{b}kitcat - 7:06{/b}\nYes MAC, fight the power!", 4, "#ffffff")
default vig4_sc3_5_comment3 = ChatEntry(False, "{b}Coriolis - 7:06{/b}\nOh, MAC...", 4, "#ffffff")
default vig4_sc3_5_comment4 = ChatEntry(False, "{b}pickledDragons - 7:06{/b}\nWell Cap, what'll it be?", 4, "#ffffff")
##Comment5 to comment29 are for saying you don't want to leave MAC behind##
default vig4_sc3_5_comment5 = ChatEntry(False, "{b}kitcat - 7:07{/b}\nYes!", 4, "#ffffff")
default vig4_sc3_5_comment6 = ChatEntry(False, "{b}turb0g00se - 7:07{/b}\nTime to make a run for it!", 4, "#ffffff")
default vig4_sc3_5_comment7 = ChatEntry(False, "{b}AFKAngel - 7:07{/b}\nHe's learned how to plan!", 4, "#ffffff")
default vig4_sc3_5_comment8 = ChatEntry(False, "{b}marxky8 - 7:07{/b}\nNo!", 4, "#ffffff")
default vig4_sc3_5_comment9 = ChatEntry(False, "{b}R4dioRobbie - 7:07{/b}\nAh so we see his true colors now", 4, "#ffffff")
default vig4_sc3_5_comment10 = ChatEntry(False, "{b}llamabama22 - 7:07{/b}\nWell, Moze and Co. are somewhat predictable", 4, "#ffffff")
default vig4_sc3_5_comment11 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:07{/b}\nMay as well be goons", 4, "#ffffff")
default vig4_sc3_5_comment12 = ChatEntry(False, "{b}R4dioRobbie - 7:07{/b}\nso they make you say bye no matter what?", 4, "#ffffff")
default vig4_sc3_5_comment13 = ChatEntry(False, "{b}kitcat - 7:07{/b}\nI can't watch", 4, "#ffffff")
default vig4_sc3_5_comment14 = ChatEntry(False, "{b}treb.ell - 7:07{/b}\nI can't look away!", 4, "#ffffff")
default vig4_sc3_5_comment15 = ChatEntry(False, "{b}pickledDragons - 7:08{/b}\nTell 'em, MAC!", 4, "#ffffff")
default vig4_sc3_5_comment16 = ChatEntry(False, "{b}Coriolis - 7:08{/b}\nAaah this hurts!", 4, "#ffffff")
default vig4_sc3_5_comment17 = ChatEntry(False, "{b}bacon8r_6 - 7:08{/b}\nI thought you were team Dragonflies?", 4, "#ffffff")
default vig4_sc3_5_comment18 = ChatEntry(False, "{b}Coriolis - 7:08{/b}\nI think letting go of MAC is the right thing to do. Doesn't mean I like it lol", 4, "#ffffff")
default vig4_sc3_5_comment19 = ChatEntry(False, "{b}AFKAngel - 7:08{/b}\noof my heart", 4, "#ffffff")
default vig4_sc3_5_comment20 = ChatEntry(False, "{b}marxky8 - 7:08{/b}\nI know, I can't take much more of this", 4, "#ffffff")
default vig4_sc3_5_comment21 = ChatEntry(False, "{b}kitcat - 7:09{/b}\nThat's it, here come the waterworks", 4, "#ffffff")
default vig4_sc3_5_comment22 = ChatEntry(False, "{b}jerrybean874 - 7:09{/b}\nThey've already been gushing on my end lol", 4, "#ffffff")
default vig4_sc3_5_comment23 = ChatEntry(False, "{b}turb0g00se - 7:09{/b}\nMom, Momma, and Mommy taught him well!", 4, "#ffffff")
default vig4_sc3_5_comment24 = ChatEntry(False, "{b}J4MIR0QU4I - 7:09{/b}\n<3", 4, "#ffffff")
default vig4_sc3_5_comment25 = ChatEntry(False, "{b}pickledDragons - 7:09{/b}\n<3", 4, "#ffffff")
default vig4_sc3_5_comment26 = ChatEntry(False, "{b}Coriolis - 7:09{/b}\n<3", 4, "#ffffff")
default vig4_sc3_5_comment27 = ChatEntry(False, "{b}_lostinmetr0 - 7:09{/b}\n<3", 4, "#ffffff")
default vig4_sc3_5_comment28 = ChatEntry(False, "{b}AFKAngel - 7:09{/b}\n<3", 4, "#ffffff")
default vig4_sc3_5_comment29 = ChatEntry(False, "{b}kitcat - 7:09{/b}\n<3", 4, "#ffffff")
##Comment30 to comment34 are for telling MAC to stay on Polaris##
default vig4_sc3_5_comment30 = ChatEntry(False, "{b}kitcat - 7:07{/b}\nNo!", 4, "#ffffff")
default vig4_sc3_5_comment31 = ChatEntry(False, "{b}_lostinmetr0 - 7:07{/b}\nThe conflict bigger than family", 4, "#ffffff")
default vig4_sc3_5_comment32 = ChatEntry(False, "{b}AFKAngel - 7:07{/b}\nNothing's bigger than family", 4, "#ffffff")
default vig4_sc3_5_comment33 = ChatEntry(False, "{b}Coriolis - 7:07{/b}\nCome on Moze, don't say goodbye like this!", 4, "#ffffff")
default vig4_sc3_5_comment34 = ChatEntry(False, "{b}marxky8 - 7:07{/b}\nGod, we're doing what you want. Don't be dicks about it", 4, "#ffffff")
##Coment35 to comment48 are for telling MAC this wasn't personal##
default vig4_sc3_5_comment35 = ChatEntry(False, "{b}kitcat - 7:07{/b}\nomg what's going on?", 4, "#ffffff")
default vig4_sc3_5_comment36 = ChatEntry(False, "{b}_lostinmetr0 - 7:07{/b}\nHe's not gonna listen so we have to lie", 4, "#ffffff")
default vig4_sc3_5_comment37 = ChatEntry(False, "{b}AFKAngel - 7:07{/b}\nNo this is the worst way to do it!", 4, "#ffffff")
default vig4_sc3_5_comment38 = ChatEntry(False, "{b}Coriolis - 7:07{/b}\nI agree with leaving him, but this is wrong. We should be honest with him, not lie", 4, "#ffffff")
default vig4_sc3_5_comment39 = ChatEntry(False, "{b}R4dioRobbie - 7:07{/b}\noh. my. god.", 4, "#ffffff")
default vig4_sc3_5_comment40 = ChatEntry(False, "{b}J4MIR0QU4I - 7:07{/b}\nbruuuutal", 4, "#ffffff")
default vig4_sc3_5_comment41 = ChatEntry(False, "{b}xXpearlXx - 7:08{/b}\nshit", 4, "#ffffff")
default vig4_sc3_5_comment42 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:08{/b}\nouch", 4, "#ffffff")
default vig4_sc3_5_comment43 = ChatEntry(False, "{b}marxky8 - 7:08{/b}\nI can't take much more of this", 4, "#ffffff")
default vig4_sc3_5_comment44 = ChatEntry(False, "{b}pickledDragons - 7:08{/b}\nOh for--shut it gramps!", 4, "#ffffff")
default vig4_sc3_5_comment45 = ChatEntry(False, "{b}kitcat - 7:09{/b}\nMAC no", 4, "#ffffff")
default vig4_sc3_5_comment46 = ChatEntry(False, "{b}_lostinmetr0 - 7:09{/b}\nrough", 4, "#ffffff")
default vig4_sc3_5_comment47 = ChatEntry(False, "{b}AFKAngel - 7:09{/b}\nmy heart", 4, "#ffffff")
default vig4_sc3_5_comment48 = ChatEntry(False, "{b}Coriolis - 7:09{/b}\nouch", 4, "#ffffff")

###Comments vig4_sc4_1 - Return to ship; Phone call with Ama
default vig4_sc4_1_comment1 = ChatEntry(False, "{b}R4dioRobbie - 7:10{/b}\nIs it over? Is that the end?", 4, "#ffffff")
default vig4_sc4_1_comment2 = ChatEntry(False, "{b}treb.ell - 7:10{/b}\nUnlikely, something's coming up soon for sure", 4, "#ffffff")
default vig4_sc4_1_comment3 = ChatEntry(False, "{b}bacon8r_6 - 7:10{/b}\nI hope you're right cause I can't handle that being the last scene", 4, "#ffffff")
default vig4_sc4_1_comment4 = ChatEntry(False, "{b}turb0g00se - 7:11{/b}\nAllistar's ghost?", 4, "#ffffff")
default vig4_sc4_1_comment5 = ChatEntry(False, "{b}xXpearlXx - 7:11{/b}\nI don't know about this...", 4, "#ffffff")
default vig4_sc4_1_comment6 = ChatEntry(False, "{b}kitcat - 7:11{/b}\nOMFG", 4, "#ffffff")
default vig4_sc4_1_comment7 = ChatEntry(False, "{b}marxky8 - 7:11{/b}\nDeadeye to the rescue?", 4, "#ffffff")
default vig4_sc4_1_comment8 = ChatEntry(False, "{b}Coriolis - 7:11{/b}\nCareful, she's dangerous", 4, "#ffffff")
default vig4_sc4_1_comment9 = ChatEntry(False, "{b}llamabama22 - 7:12{/b}\nOk so Moze is crashing out", 4, "#ffffff")
default vig4_sc4_1_comment10 = ChatEntry(False, "{b}_lostinmetr0 - 7:12{/b}\nDamn, let her know how you really feel", 4, "#ffffff")
default vig4_sc4_1_comment11 = ChatEntry(False, "{b}marxky8 - 7:12{/b}\nI say again - Deadeye to the rescue???", 4, "#ffffff")
default vig4_sc4_1_comment12 = ChatEntry(False, "{b}R4dioRobbie - 7:12{/b}\nooooh shield papa done messed up", 4, "#ffffff")
default vig4_sc4_1_comment13 = ChatEntry(False, "{b}jerrybean784 - 7:12{/b}\nomg this is so different from the \"normal\" path", 4, "#ffffff")
default vig4_sc4_1_comment14 = ChatEntry(False, "{b}treb.ell - 7:12{/b}\nwdym", 4, "#ffffff")
default vig4_sc4_1_comment15 = ChatEntry(False, "{b}jerrybean784 - 7:12{/b}\nIf you Allistar surives in the beginning, he breaks his communicator in Episode 3", 4, "#ffffff")
default vig4_sc4_1_comment16 = ChatEntry(False, "{b}jerrybean784 - 7:12{/b}\nThis call with Ama never happens", 4, "#ffffff")
default vig4_sc4_1_comment17 = ChatEntry(False, "{b}Coriolis - 7:13{/b}\nSo because we killed Allistar back in Episode 1...", 4, "#ffffff")
default vig4_sc4_1_comment18 = ChatEntry(False, "{b}kitcat - 7:13{/b}\nThat means we can ally with Ama in Episode 4?!?!", 4, "#ffffff")
default vig4_sc4_1_comment19 = ChatEntry(False, "{b}pickledDragons - 7:13{/b}\n[streamer] with the long con!", 4, "#ffffff")
default vig4_sc4_1_comment20 = ChatEntry(False, "{b}AFKAngel - 7:13{/b}\nGOAT status!", 4, "#ffffff")
default vig4_sc4_1_comment21 = ChatEntry(False, "{b}turb0g00se - 7:13{/b}\nLegend!", 4, "#ffffff")
default vig4_sc4_1_comment22 = ChatEntry(False, "{b}xXpearlXx - 7:13{/b}\nso the Ama romance is still on the table???", 4, "#ffffff")
default vig4_sc4_1_comment23 = ChatEntry(False, "{b}treb.ell - 7:13{/b}\nLet's do it! Why see what everyone else is seeing!", 4, "#ffffff")
default vig4_sc4_1_comment24 = ChatEntry(False, "{b}marxky8 - 7:14{/b}\nyes", 4, "#ffffff")
default vig4_sc4_1_comment25 = ChatEntry(False, "{b}turb0g00se - 7:14{/b}\nhell yes", 4, "#ffffff")
default vig4_sc4_1_comment26 = ChatEntry(False, "{b}kitcat - 7:14{/b}\nkiss her!", 4, "#ffffff")
default vig4_sc4_1_comment27 = ChatEntry(False, "{b}bacon8r_6 - 7:14{/b}\nShield Papa is going down!", 4, "#ffffff")
default vig4_sc4_1_comment28 = ChatEntry(False, "{b}_lostinmetr0 - 7:14{/b}\nOk, I wasn't on board before, but this is pretty hype!", 4, "#ffffff")
default vig4_sc4_1_comment29 = ChatEntry(False, "{b}Coriolis - 7:14{/b}\nCool! But don't let her get the jump on you! She might still try to steal MAC for herself!", 4, "#ffffff")
default vig4_sc4_1_comment30 = ChatEntry(False, "{b}AFKAngel - 7:14{/b}\nTurn the ship around! We have a child to save!", 4, "#ffffff")
default vig4_sc4_1_comment31 = ChatEntry(True, "{b}kitcat - 7:14{/b}\nAwww but y tho?", 4, "#ffffff", "vig4_sc4_kcNoOffer")
default vig4_sc4_1_comment32 = ChatEntry(False, "{b}J4MIR0QU4I - 7:14{/b}\nMoze isn't wrong", 4, "#ffffff")
default vig4_sc4_1_comment33 = ChatEntry(False, "{b}jerrybean784 - 7:14{/b}\nthe safe move probably", 4, "#ffffff")
default vig4_sc4_1_comment34 = ChatEntry(False, "{b}Coriolis - 7:14{/b}\nWe can't trust Deadeye, this was the only move", 4, "#ffffff")

###Comments vig4_sc4_2 - Debrief Ama call with crew
default vig4_sc4_2_comment1 = ChatEntry(False, "{b}turb0g00se - 7:15{/b}\nThey prolly think Moze has lost it lol", 4, "#ffffff")
default vig4_sc4_2_comment2 = ChatEntry(False, "{b}_lostinmetr0 - 7:15{/b}\ntbf, she's kinda been losing it lol", 4, "#ffffff")
default vig4_sc4_2_comment3 = ChatEntry(False, "{b}R4dioRobbie - 7:15{/b}\nthird act climax here we come!", 4, "#ffffff")
default vig4_sc4_2_comment4 = ChatEntry(False, "{b}bacon8r_6 - 7:15{/b}\nGetting the SnakeHawks back together!", 4, "#ffffff")
default vig4_sc4_2_comment5 = ChatEntry(False, "{b}marxky8 - 7:15{/b}\nCome on Jenn, get on board!", 4, "#ffffff")
default vig4_sc4_2_comment6 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:15{/b}\nI get it, we can't trust her. Still disappointed", 4, "#ffffff")
default vig4_sc4_2_comment7 = ChatEntry(False, "{b}treb.ell - 7:15{/b}\nMoze for sure {i}wants{/i} to trust Ama. But is it a good idea? That's for our [streamer] to decide :)", 4, "#ffffff")
default vig4_sc4_2_comment8 = ChatEntry(False, "{b}pickledDragons - 7:16{/b}\nBurn it to the ground", 4, "#ffffff", "vig4_sc4_kcNoOffer")
default vig4_sc4_2_comment9 = ChatEntry(False, "{b}Coriolis - 7:16{/b}\nJust because Coil's a jerk doesn't mean the rest of the town should die! BigCorp is the enemy, we can't forget that", 4, "#ffffff")
default vig4_sc4_2_comment10 = ChatEntry(False, "{b}kitcat - 7:16{/b}\n@Coriolis - that's true, but he is a really {i}big{/i} jerk", 4, "#ffffff")
default vig4_sc4_2_comment11 = ChatEntry(False, "{b}_lostinmetr0 - 7:16{/b}\nThat's my Captain!", 4, "#ffffff")
default vig4_sc4_2_comment12 = ChatEntry(False, "{b}treb.ell - 7:16{/b}\nMarshal Moze reporting for duty!", 4, "#ffffff")
default vig4_sc4_2_comment13 = ChatEntry(False, "{b}turb0g00se - 7:16{/b}\nShield Papa is going down!", 4, "#ffffff")
default vig4_sc4_2_comment14 = ChatEntry(False, "{b}treb.ell - 7:16{/b}\nOutlaw Moze is here to stay!", 4, "#ffffff")

###Comments vig4_sc4_3 - Oakley crash
default vig4_sc4_3_comment1 = ChatEntry(False, "{b}llamabama22 - 7:17{/b}\nOh god, what now?", 4, "#ffffff")
default vig4_sc4_3_comment2 = ChatEntry(False, "{b}_lostinmetr0 - 7:17{/b}\nNot good", 4, "#ffffff")
default vig4_sc4_3_comment3 = ChatEntry(False, "{b}bacon8r_6 - 7:17{/b}\nRiiiight now we have to deal with them", 4, "#ffffff")
default vig4_sc4_3_comment4 = ChatEntry(False, "{b}xXpearlXx - 7:17{/b}\noh shit", 4, "#ffffff")
default vig4_sc4_3_comment5 = ChatEntry(False, "{b}Coriolis - 7:17{/b}\nC'mon Jenn!", 4, "#ffffff")
default vig4_sc4_3_comment6 = ChatEntry(False, "{b}treb.ell - 7:18{/b}\nomg", 4, "#ffffff")
default vig4_sc4_3_comment7 = ChatEntry(False, "{b}marxky8 - 7:18{/b}\nwhat's gonna happen?", 4, "#ffffff")

###Comments vig4_sc5_0 - Oakley flashback
default vig4_sc5_0_comment1 = ChatEntry(False, "{b}turb0g00se - 7:19{/b}\nWait, what's going on?", 4, "#ffffff")
default vig4_sc5_0_comment2 = ChatEntry(False, "{b}R4dioRobbie - 7:19{/b}\nAre we dead?", 4, "#ffffff")
default vig4_sc5_0_comment3 = ChatEntry(False, "{b}treb.ell - 7:19{/b}\nNo this is a memory", 4, "#ffffff")
default vig4_sc5_0_comment4 = ChatEntry(False, "{b}pickledDragons - 7:19{/b}\nIt's the ship!", 4, "#ffffff")
default vig4_sc5_0_comment5 = ChatEntry(False, "{b}kitcat - 7:19{/b}\nwait this is cute, why are they making this so cute??", 4, "#ffffff")

###Comments vig4_sc5_1 - Oakley in ruins; Plan for Polaris
default vig4_sc5_1_comment1 = ChatEntry(False, "{b}jerrybean784 - 7:20{/b}\nCap is in a roooough state", 4, "#ffffff")
default vig4_sc5_1_comment2 = ChatEntry(False, "{b}J4MIR0QU4I - 7:20{/b}\nAt least she's alive", 4, "#ffffff")
default vig4_sc5_1_comment3 = ChatEntry(False, "{b}_lostinmetr0 - 7:20{/b}\nPhew, the crew made it!", 4, "#ffffff")
default vig4_sc5_1_comment4 = ChatEntry(False, "{b}Coriolis - 7:20{/b}\nAh, I love them together", 4, "#ffffff")
default vig4_sc5_1_comment5 = ChatEntry(False, "{b}kitcat - 7:20{/b}\nAh, I love them together", 4, "#ffffff")
default vig4_sc5_1_comment6 = ChatEntry(False, "{b}AFKAngel - 7:20{/b}\nThe date scene feels like it was a lifetime ago, so much has happened since then", 4, "#ffffff")
default vig4_sc5_1_comment7 = ChatEntry(False, "{b}xXpearlXx - 7:21{/b}\nYa for sure there's no brain damage to worry about", 4, "#ffffff")
default vig4_sc5_1_comment8 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:21{/b}\nTeresa always clutch", 4, "#ffffff")
default vig4_sc5_1_comment9 = ChatEntry(False, "{b}pickledDragons - 7:21{/b}\nHoly shit", 4, "#ffffff")
default vig4_sc5_1_comment10 = ChatEntry(False, "{b}Coriolis - 7:21{/b}\nI'm gonna cry", 4, "#ffffff")
default vig4_sc5_1_comment11 = ChatEntry(False, "{b}kitcat - 7:21{/b}\nRIGHT AFTER THE FLASHBACK OF COURSE!", 4, "#ffffff")
default vig4_sc5_1_comment12 = ChatEntry(False, "{b}bacon8r_6 - 7:21{/b}\nwell there's only one way to go now", 4, "#ffffff")
default vig4_sc5_1_comment13 = ChatEntry(False, "{b}R4dioRobbie - 7:21{/b}\nYeah, through Coil's face", 4, "#ffffff")
default vig4_sc5_1_comment14 = ChatEntry(False, "{b}llamabama22 - 7:21{/b}\nWe don't have to kill Shield Papa", 4, "#ffffff")
default vig4_sc5_1_comment15 = ChatEntry(False, "{b}J4MIR0QU4I - 7:21{/b}\nNah this is on the company. I'd rather smash up BigCorp", 4, "#ffffff")
default vig4_sc5_1_comment16 = ChatEntry(False, "{b}turb0g00se - 7:22{/b}\nPolaris is screwed", 4, "#ffffff")
default vig4_sc5_1_comment17 = ChatEntry(False, "{b}marxky8 - 7:22{/b}\nWe're looking pretty screwed atm", 4, "#ffffff")
default vig4_sc5_1_comment18 = ChatEntry(False, "{b}xXpearlXx - 7:22{/b}\nIt does remind you who the real villains are", 4, "#ffffff")
default vig4_sc5_1_comment19 = ChatEntry(False, "{b}pickledDragons - 7:22{/b}\nI don't like Coil, obviously. But BC's worse, I'll grant that.", 4, "#ffffff")
default vig4_sc5_1_comment20 = ChatEntry(False, "{b}kitcat - 7:23{/b}\nYeah go MAC! Blow 'em outta the sky!", 4, "#ffffff")
default vig4_sc5_1_comment21 = ChatEntry(False, "{b}kitcat - 7:23{/b}\nYeah go nurse MAC!", 4, "#ffffff")
default vig4_sc5_1_comment22 = ChatEntry(False, "{b}_lostinmetr0 - 7:23{/b}\nDon't get obsessed", 4, "#ffffff")
default vig4_sc5_1_comment23 = ChatEntry(False, "{b}jerrybean784 - 7:23{/b}\nSetting the stakes before the final battle, nice.", 4, "#ffffff")
default vig4_sc5_1_comment24 = ChatEntry(False, "{b}R4dioRobbie - 7:24{/b}\nThis is it", 4, "#ffffff")
default vig4_sc5_1_comment25 = ChatEntry(False, "{b}bacon84_6 - 7:24{/b}\nThe final countdown", 4, "#ffffff")
default vig4_sc5_1_comment26 = ChatEntry(False, "{b}pickledDragons - 7:24{/b}\nHell yeah Cap, get me hype!", 4, "#ffffff")
default vig4_sc5_1_comment27 = ChatEntry(False, "{b}J4MIR0QU4I - 7:24{/b}\nI'm getting goosebumps", 4, "#ffffff")
default vig4_sc5_1_comment28 = ChatEntry(True, "{b}Coriolis - 7:24{/b}\nReady to bring this to a close, Cap?", 4, "#ffffff", "vig_sc5_csClimax")

###Comments vig4_sc5_2 - Rendezvous with Ama
default vig4_sc5_2_comment1 = ChatEntry(False, "{b}kitcat - 7:25{/b}\naahhh I'm crushing so hard!", 4, "#ffffff")
default vig4_sc5_2_comment2 = ChatEntry(False, "{b}xXpearlXx - 7:25{/b}\nWeren't you team \"Moresa\"?", 4, "#ffffff")
default vig4_sc5_2_comment3 = ChatEntry(False, "{b}kitcat - 7:25{/b}\nBefore I knew this was an option, ya. Now I'm team Amoze!", 4, "#ffffff")
default vig4_sc5_2_comment4 = ChatEntry(False, "{b}Coriolis - 7:25{/b}\nI always forget cause of the whole \"trying to kill us\" thing - but she's so cool", 4, "#ffffff")
default vig4_sc5_2_comment5 = ChatEntry(False, "{b}xxxP0tat0Pr0phetxxx - 7:25{/b}\nCome on ladies, same team, focus up!", 4, "#ffffff")
default vig4_sc5_2_comment6 = ChatEntry(False, "{b}_lostinmetr0 - 7:25{/b}\nKeep her at a distance, smart", 4, "#ffffff")
default vig4_sc5_2_comment7 = ChatEntry(False, "{b}bacon8r_6 - 7:25{/b}\nI love their back and forth", 4, "#ffffff")
default vig4_sc5_2_comment8 = ChatEntry(False, "{b}AFKAngel - 7:26{/b}\nNow that's a crew right there", 4, "#ffffff")
default vig4_sc5_2_comment9 = ChatEntry(False, "{b}llamabama22 - 7:26{/b}\nCome on, Ama, get on board", 4, "#ffffff")
default vig4_sc5_2_comment10 = ChatEntry(False, "{b}turb0g00se - 7:26{/b}\nRiding to war with the Deadeye!", 4, "#ffffff")


#######DEFEND POLARIS ROUTE#########

###Comments vig4_sc6_defend_1 - Steal BC tank

###Comments vig4_sc6_defend_2 - Defend Plaza

###Comments vig4_sc6_defend_3_barricade - Pull defense back to Barricade

###Comments vig4_sc6_defend_3_frontline - Go out on a limb to save DFlies

###Comments vig4_sc6_defend_4 - Tank destroyed

###Comments vig4_sc6_defend_5 - Moze enters tower

###Comments vig4_sc7_1_defend - Moze meets Coil and Ama

#######ATTACK POLARIS ROUTE (AMA) #########

###Comments vig4_sc6_attack_1_ama - Identify tank

###Comments vig4_sc6_attack_1_assault_ama - steal tank and save hostages

###Comments vig4_sc6_attack_1_split_ama - steal tank and let BC keep hostages

###Comments vig4_sc6_attack_2_ama - Tank onboarding scene

###Comments vig4_sc6_attack_3_ama - Tank assaults plaza

###Comments vig4_sc7_1_attack_ama - Ama and Moze meet Coil

#########ATTACK POLARIS ROUTE###########

###Comments vig4_sc6_attack_1 - Identify tank

###Comments vig4_sc6_attack_1_assault - steal tank and save hostages

###Comments vig4_sc6_attack_1_split - steal tank and let BC keep hostages

###Comments vig4_sc6_attack_2 - Tank onboarding scene

###Comments vig4_sc6_attack_3 - Tank assaults plaza

###Comments vig4_sc7_1_attack - Ama and Moze meet Coil

#######SCENE 7#########

###Comments vig4_sc7_2 - Coil lays out the stakes and sets the final decision

###Comments vig4_sc7_3_ama - Final boss VS Coil

###Comments vig4_sc7_3_coil - Final boss vs Ama

####EPILOGUE#####

###Comments vig4_epilogue_ama - Epilogue (Ama allied)

###Comments vig4_epilogue_coil Epilogue (Coil allied)




#### BLUEIT THREADS #####
default vig4_bThread1 = bThread( 3, "vig4_blueit_endgamethread", "images/socials/bThread_v4_endgame.png") #tag, target, image
